using System.Text;

using MinimalOpenAPI.Abstractions.Models;

namespace MinimalOpenAPI.Generator.CodeGen;

/// <summary>
/// Generates the DI registration extension method for all discovered handlers.
/// </summary>
internal static class DependencyInjectionRegistrationGenerator
{
    public static string Generate(
        List<OpenApiOperation> operations,
        List<DiscoveredImplementation> handlers,
        List<DiscoveredImplementation> customizers,
        string rootNamespace,
        string specName)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using global::Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine($"namespace {rootNamespace}.{specName}.Endpoints;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>Generated DI registration for MinimalOpenAPI handlers.</summary>");
        TypeMapper.AppendGeneratedAttributes(sb);
        sb.AppendLine("public static class MinimalOpenApiGeneratedServiceCollectionExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Registers all generated endpoint handlers and registration customizers.</summary>");
        sb.AppendLine("    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddGeneratedEndpoints(");
        sb.AppendLine("        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine("    {");

        foreach (var op in operations)
        {
            var handlerBase = TypeMapper.HandlerClassName(op.OperationId);
            var handlerImpl = handlers.FirstOrDefault(h => h.BaseName == handlerBase);
            if (handlerImpl is not null)
            {
                // Register concrete implementation
                sb.AppendLine($"        services.AddScoped<{rootNamespace}.{specName}.Endpoints.{handlerBase}, {handlerImpl.FullName}>();");
            }
            else
            {
                // No implementation found — register the base class so the endpoint resolves at runtime
                // (it will throw NotImplementedException when invoked, matching the MOA001 warning)
                sb.AppendLine($"        services.AddScoped<{rootNamespace}.{specName}.Endpoints.{handlerBase}>();");
            }

            var customizerBase = TypeMapper.RegistrationClassName(op.OperationId);
            var customizerImpl = customizers.FirstOrDefault(c => c.BaseName == customizerBase);
            if (customizerImpl is not null)
            {
                sb.AppendLine($"        services.AddSingleton<{rootNamespace}.{specName}.Endpoints.{customizerBase}, {customizerImpl.FullName}>();");
            }
        }

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Wires <see cref=\"MinimalOpenApiGeneratedServiceCollectionExtensions.AddGeneratedEndpoints\"/>");
        sb.AppendLine("/// into <see cref=\"global::MinimalOpenAPI.ServiceCollectionExtensions.AddMinimalOpenApi\"/>");
        sb.AppendLine("/// and registers the endpoint mapping delegate with");
        sb.AppendLine("/// <see cref=\"global::MinimalOpenAPI.ServiceCollectionExtensions.MapMinimalOpenApiEndpoints\"/>,");
        sb.AppendLine("/// so the consumer only calls <c>services.AddMinimalOpenApi()</c> and");
        sb.AppendLine("/// <c>app.MapMinimalOpenApiEndpoints()</c>.");
        sb.AppendLine("/// </summary>");
        TypeMapper.AppendGeneratedAttributes(sb);
        sb.AppendLine("internal static class MinimalOpenApiModuleInitializer");
        sb.AppendLine("{");
        sb.AppendLine("    [global::System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine("    internal static void Register()");
        sb.AppendLine("    {");
        sb.AppendLine("        global::MinimalOpenAPI.ServiceCollectionExtensions");
        sb.AppendLine("            .RegisterGeneratedServices(services => services.AddGeneratedEndpoints());");
        sb.AppendLine($"        global::MinimalOpenAPI.ServiceCollectionExtensions.RegisterEndpointMapping(");
        sb.AppendLine($"            (builder, group) => global::{rootNamespace}.{specName}.Endpoints.MinimalOpenApiGeneratedEndpointRouteBuilderExtensions.MapEndpoints(builder, group));");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }
}

/// <summary>Represents a discovered concrete implementation of a generated base class.</summary>
internal sealed class DiscoveredImplementation
{
    public string BaseName { get; init; } = string.Empty;
    public string FullName { get; init; } = string.Empty;
}