using System.Text;

using MinimalOpenAPI.Abstractions.Models;

namespace MinimalOpenAPI.Generator.CodeGen;

/// <summary>
/// Generates sealed record DTOs and C# enums from OpenAPI component schemas.
/// </summary>
internal static class DtoGenerator
{
    public static DtoGenerationResult Generate(
        Dictionary<string, OpenApiSchema> schemas,
        string rootNamespace,
        string specName,
        SchemaDirectionalityAnalysis directionality,
        SchemaNameMap schemaNameMap)
    {
        if (schemas.Count == 0) return new DtoGenerationResult(string.Empty, []);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using global::System.Text.Json.Serialization;");
        sb.AppendLine();
        sb.AppendLine($"namespace {rootNamespace}.{specName}.Contracts;");
        sb.AppendLine();

        var emitted = new HashSet<string>(StringComparer.Ordinal);
        var allOfConflicts = new List<AllOfPropertyConflict>();

        // First pass: emit top-level enum schemas.
        foreach (var kvp in schemas)
        {
            if (kvp.Value.Enum is not null)
            {
                var normalizedName = schemaNameMap.GetTypeName(kvp.Key);
                GenerateEnum(sb, normalizedName, kvp.Value, emitted);
            }
        }

        // Second pass: emit neutral object schemas as records (with recursive inline-object
        // and inline-enum dependency emission handled inside EmitRecordTree).
        foreach (var kvp in schemas)
        {
            var name = kvp.Key;
            var schema = kvp.Value;
            if (schema.Enum is not null) continue;
            var resolvedSchema = AllOfSchemaFlattener.Resolve(schema, schemas, name, allOfConflicts);
            if (resolvedSchema.Type != "object" && resolvedSchema.Reference is null && resolvedSchema.Properties.Count == 0)
                continue;
            if (TypeMapper.IsDictionarySchema(resolvedSchema))
                continue; // pure-dictionary schemas map to Dictionary<string, T> at the use site

            var normalizedName = schemaNameMap.GetTypeName(name);
            EmitRecordTree(sb, normalizedName, resolvedSchema, schemas, emitted, allOfConflicts, directionality, SchemaGenerationScope.Neutral);
        }

        // Third pass: emit scoped request/response variants only when required.
        foreach (var kvp in schemas)
        {
            var name = kvp.Key;
            var schema = kvp.Value;
            if (schema.Enum is not null) continue;

            var resolvedSchema = AllOfSchemaFlattener.Resolve(schema, schemas, name, allOfConflicts);
            if (resolvedSchema.Type != "object" && resolvedSchema.Reference is null && resolvedSchema.Properties.Count == 0)
                continue;
            if (TypeMapper.IsDictionarySchema(resolvedSchema))
                continue;

            var normalizedName = schemaNameMap.GetTypeName(name);

            if (directionality.ShouldGenerateScope(name, SchemaGenerationScope.Request))
            {
                EmitRecordTree(
                    sb,
                    normalizedName + "Request",
                    resolvedSchema,
                    schemas,
                    emitted,
                    allOfConflicts,
                    directionality,
                    SchemaGenerationScope.Request);
            }

            if (directionality.ShouldGenerateScope(name, SchemaGenerationScope.Response))
            {
                EmitRecordTree(
                    sb,
                    normalizedName + "Response",
                    resolvedSchema,
                    schemas,
                    emitted,
                    allOfConflicts,
                    directionality,
                    SchemaGenerationScope.Response);
            }
        }

        return new DtoGenerationResult(sb.ToString(), allOfConflicts);
    }

    /// <summary>
    /// Recursively emits the record for <paramref name="schema"/> and all records (and enums)
    /// for its inline properties, ensuring each dependency is emitted before its parent.
    /// The <paramref name="emitted"/> set provides cycle detection and deduplication.
    /// </summary>
    private static void EmitRecordTree(
        StringBuilder sb,
        string name,
        OpenApiSchema schema,
        Dictionary<string, OpenApiSchema> allSchemas,
        HashSet<string> emitted,
        List<AllOfPropertyConflict> allOfConflicts,
        SchemaDirectionalityAnalysis directionality,
        SchemaGenerationScope scope)
    {
        if (!emitted.Add(name))
            return; // already emitted or cycle guard

        var resolvedSchema = AllOfSchemaFlattener.Resolve(schema, allSchemas, name, allOfConflicts);

        // Emit inline enum property types (dependencies) before the parent record.
        foreach (var propKvp in resolvedSchema.Properties)
        {
            if (propKvp.Value.Enum is not null)
            {
                var inlineEnumName = name + TypeMapper.ToPascalCase(propKvp.Key);
                GenerateEnum(sb, inlineEnumName, propKvp.Value, emitted);
            }
        }

        // Emit inline-object property types (dependencies) before the parent record.
        foreach (var propKvp in resolvedSchema.Properties)
        {
            if (!directionality.ShouldIncludeProperty(propKvp.Value, scope))
                continue;

            if (TypeMapper.IsInlineObject(propKvp.Value))
            {
                var nestedName = name + TypeMapper.ToPascalCase(propKvp.Key);
                EmitRecordTree(sb, nestedName, propKvp.Value, allSchemas, emitted, allOfConflicts, directionality, scope);
            }
        }

        // Emit inline-object value types for dictionary properties (dependencies) before the parent record.
        foreach (var propKvp in resolvedSchema.Properties)
        {
            if (!directionality.ShouldIncludeProperty(propKvp.Value, scope))
                continue;

            if (TypeMapper.IsDictionarySchema(propKvp.Value)
                && propKvp.Value.AdditionalProperties is { } valueSchema
                && TypeMapper.IsInlineObject(valueSchema))
            {
                var valueName = name + TypeMapper.ToPascalCase(propKvp.Key) + "Value";
                EmitRecordTree(sb, valueName, valueSchema, allSchemas, emitted, allOfConflicts, directionality, scope);
            }
        }

        // Emit inline-object and inline-enum item types for array properties (dependencies) before the parent record.
        foreach (var propKvp in resolvedSchema.Properties)
        {
            if (!directionality.ShouldIncludeProperty(propKvp.Value, scope))
                continue;

            if (propKvp.Value.Type?.ToLowerInvariant() == "array" && propKvp.Value.Items is { } itemSchema)
            {
                var itemName = name + TypeMapper.ToPascalCase(propKvp.Key) + "Item";
                EmitArrayItemSchema(sb, itemSchema, itemName, allSchemas, emitted, allOfConflicts, directionality, scope);
            }
        }

        // Build a resolver that maps each inline schema instance to its derived name.
        var inlineMap = new Dictionary<OpenApiSchema, string>();
        foreach (var propKvp in resolvedSchema.Properties)
        {
            if (!directionality.ShouldIncludeProperty(propKvp.Value, scope))
                continue;

            if (TypeMapper.IsInlineObject(propKvp.Value) || propKvp.Value.Enum is not null)
                inlineMap[propKvp.Value] = name + TypeMapper.ToPascalCase(propKvp.Key);
        }

        // Also map inline-object value types for dictionary properties.
        foreach (var propKvp in resolvedSchema.Properties)
        {
            if (!directionality.ShouldIncludeProperty(propKvp.Value, scope))
                continue;

            if (TypeMapper.IsDictionarySchema(propKvp.Value)
                && propKvp.Value.AdditionalProperties is { } valueSchema
                && TypeMapper.IsInlineObject(valueSchema))
                inlineMap[valueSchema] = name + TypeMapper.ToPascalCase(propKvp.Key) + "Value";
        }

        // Also map inline-object and inline-enum item types for array properties.
        foreach (var propKvp in resolvedSchema.Properties)
        {
            if (!directionality.ShouldIncludeProperty(propKvp.Value, scope))
                continue;

            if (propKvp.Value.Type?.ToLowerInvariant() == "array" && propKvp.Value.Items is { } itemSchema)
            {
                var itemName = name + TypeMapper.ToPascalCase(propKvp.Key) + "Item";
                BuildArrayItemInlineMap(itemSchema, itemName, inlineMap);
            }
        }

        InlineSchemaResolver? resolveInline = inlineMap.Count > 0
            ? s => inlineMap.TryGetValue(s, out var n) ? n : null
            : null;

        GenerateRecord(sb, name, resolvedSchema, directionality, scope, resolveInline);
        sb.AppendLine();
    }

    /// <summary>
    /// Emits the record or enum for an array item schema, recursing into inner items when
    /// the item schema is itself an array (array-of-array support).
    /// </summary>
    private static void EmitArrayItemSchema(
        StringBuilder sb,
        OpenApiSchema itemSchema,
        string itemName,
        Dictionary<string, OpenApiSchema> allSchemas,
        HashSet<string> emitted,
        List<AllOfPropertyConflict> allOfConflicts,
        SchemaDirectionalityAnalysis directionality,
        SchemaGenerationScope scope)
    {
        if (TypeMapper.IsInlineObject(itemSchema))
        {
            EmitRecordTree(sb, itemName, itemSchema, allSchemas, emitted, allOfConflicts, directionality, scope);
        }
        else if (itemSchema.Enum is not null)
        {
            GenerateEnum(sb, itemName, itemSchema, emitted);
        }
        else if (itemSchema.Type?.ToLowerInvariant() == "array" && itemSchema.Items is { } innerItemSchema)
        {
            // array-of-array: walk into the inner item schema using an extra "Item" suffix.
            EmitArrayItemSchema(sb, innerItemSchema, itemName + "Item", allSchemas, emitted, allOfConflicts, directionality, scope);
        }
    }

    /// <summary>
    /// Populates <paramref name="inlineMap"/> with inline schema → type-name entries for
    /// array item schemas, recursing through nested arrays (array-of-array support).
    /// </summary>
    private static void BuildArrayItemInlineMap(
        OpenApiSchema itemSchema,
        string itemName,
        Dictionary<OpenApiSchema, string> inlineMap)
    {
        if (TypeMapper.IsInlineObject(itemSchema) || itemSchema.Enum is not null)
        {
            inlineMap[itemSchema] = itemName;
        }
        else if (itemSchema.Type?.ToLowerInvariant() == "array" && itemSchema.Items is { } innerItemSchema)
        {
            BuildArrayItemInlineMap(innerItemSchema, itemName + "Item", inlineMap);
        }
    }

    private static void GenerateEnum(
        StringBuilder sb,
        string name,
        OpenApiSchema schema,
        HashSet<string> emitted)
    {
        if (!emitted.Add(name))
            return; // already emitted

        sb.AppendLine($"/// <summary>Generated enum for schema <c>{name}</c>.</summary>");
        sb.AppendLine($"[global::System.CodeDom.Compiler.GeneratedCode(\"{TypeMapper.GeneratorName}\", \"{TypeMapper.GeneratorVersion}\")]");
        sb.AppendLine("[JsonConverter(typeof(JsonStringEnumConverter))]");
        sb.AppendLine($"public enum {name}");
        sb.AppendLine("{");

        var values = schema.Enum!;
        for (var i = 0; i < values.Count; i++)
        {
            var member = TypeMapper.ToEnumMemberName(values[i]);
            sb.Append($"    {member}");
            sb.AppendLine(i < values.Count - 1 ? "," : string.Empty);
        }

        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void GenerateRecord(
        StringBuilder sb,
        string name,
        OpenApiSchema schema,
        SchemaDirectionalityAnalysis directionality,
        SchemaGenerationScope scope,
        InlineSchemaResolver? resolveInline = null)
    {
        sb.AppendLine($"/// <summary>Generated DTO for schema <c>{name}</c>.</summary>");
        TypeMapper.AppendGeneratedAttributes(sb);
        sb.AppendLine($"public sealed record {name}");
        sb.AppendLine("{");
        var hadDeclaredProperties = schema.Properties.Count > 0;

        foreach (var propKvp in schema.Properties)
        {
            var propName = propKvp.Key;
            var propSchema = propKvp.Value;
            if (!directionality.ShouldIncludeProperty(propSchema, scope))
                continue;
            var isRequired = schema.Required.Contains(propName, StringComparer.OrdinalIgnoreCase);
            var nullable = propSchema.Nullable || !isRequired;
            var typeName = TypeMapper.MapSchema(
                propSchema,
                nullable: nullable,
                resolveInline: resolveInline,
                resolveReference: referenceName => directionality.ResolveSchemaReference(referenceName, scope));
            var csharpName = TypeMapper.ToPascalCase(propName);

            sb.AppendLine($"    [JsonPropertyName(\"{propName}\")]");

            foreach (var attr in ValidationAttributeEmitter.GetAttributes(propSchema, "    "))
                sb.AppendLine(attr);

            if (nullable)
            {
                sb.AppendLine($"    public {typeName} {csharpName} {{ get; init; }}");
            }
            else
            {
                sb.AppendLine($"    public required {typeName} {csharpName} {{ get; init; }}");
            }
        }

        // When additionalProperties: true is set alongside named properties, capture
        // any extra key-value pairs via [JsonExtensionData].
        if (schema.AdditionalPropertiesAllowed && hadDeclaredProperties)
        {
            sb.AppendLine($"    [JsonExtensionData]");
            sb.AppendLine($"    public global::System.Collections.Generic.Dictionary<string, global::System.Text.Json.JsonElement>? Extensions {{ get; init; }}");
        }

        sb.AppendLine("}");
    }
}

internal sealed record DtoGenerationResult(
    string Source,
    IReadOnlyList<AllOfPropertyConflict> AllOfConflicts);