using System.Text;

using MinimalOpenAPI.Abstractions.Models;

namespace MinimalOpenAPI.Generator.CodeGen;

/// <summary>
/// Generates the MapEndpoints extension method that maps all operations.
/// </summary>
internal static class EndpointMappingGenerator
{
    public static string Generate(
        List<OpenApiOperation> operations,
        List<DiscoveredImplementation> customizers,
        string rootNamespace,
        string specName)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using global::Microsoft.AspNetCore.Http;");
        sb.AppendLine("using global::Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine($"namespace {rootNamespace}.{specName}.Endpoints;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>Generated endpoint mapper for MinimalOpenAPI (internal implementation detail).</summary>");
        sb.AppendLine("internal static class MinimalOpenApiGeneratedEndpointRouteBuilderExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Maps all generated endpoints onto <paramref name=\"group\"/>.</summary>");
        sb.AppendLine("    internal static void MapEndpoints(");
        sb.AppendLine("        global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder builder,");
        sb.AppendLine("        global::Microsoft.AspNetCore.Routing.RouteGroupBuilder group)");
        sb.AppendLine("    {");
        sb.AppendLine("        var services = builder.ServiceProvider;");
        sb.AppendLine();

        foreach (var op in operations)
        {
            GenerateEndpointMapping(sb, op, customizers, rootNamespace, specName);
            sb.AppendLine();
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void GenerateEndpointMapping(
        StringBuilder sb,
        OpenApiOperation operation,
        List<DiscoveredImplementation> customizers,
        string rootNamespace,
        string specName)
    {
        var contractsNs = $"{rootNamespace}.{specName}.Contracts";
        // Fully-qualified name of the handler base class (e.g. "global::NS.Spec.Endpoints.CreateOrderEndpointBase").
        var handlerFqn = $"global::{rootNamespace}.{specName}.Endpoints.{TypeMapper.HandlerClassName(operation.OperationId)}";
        var handlerClass = $"{rootNamespace}.{specName}.Endpoints.{TypeMapper.HandlerClassName(operation.OperationId)}";
        var customizerClass = $"{rootNamespace}.{specName}.Endpoints.{TypeMapper.RegistrationClassName(operation.OperationId)}";
        var constrainedRoute = TypeMapper.BuildConstrainedRoute(operation.Route, operation.Parameters);

        // Resolver: inline schema → FULLY-QUALIFIED nested type name for use outside the class.
        InlineSchemaResolver inlineResolver = s =>
        {
            if (operation.RequestBody?.Schema is { } reqSchema
                && ReferenceEquals(s, reqSchema)
                && TypeMapper.IsInlineObject(reqSchema))
                return $"{handlerFqn}.{TypeMapper.GetInlineRequestBodyTypeName()}";

            foreach (var r in operation.Responses)
            {
                if (r.Schema is { } respSchema
                    && ReferenceEquals(s, respSchema)
                    && TypeMapper.IsInlineObject(respSchema))
                    return $"{handlerFqn}.{TypeMapper.GetInlineResponseTypeName(r.StatusCode)}";
            }
            return null;
        };

        var lambdaParams = BuildLambdaParams(operation, handlerClass, contractsNs, inlineResolver);
        var handlerInvocation = BuildHandlerInvocation(operation);
        var httpMethod = TypeMapper.ToPascalCase(operation.HttpMethod.ToLowerInvariant());
        var varName = TypeMapper.ToCamelCase(TypeMapper.HandlerClassName(operation.OperationId));

        sb.AppendLine($"        // {operation.OperationId}");
        sb.AppendLine($"        var {varName} = group.Map{httpMethod}(");
        sb.AppendLine($"            \"{constrainedRoute}\",");
        sb.AppendLine($"            static ({lambdaParams})");
        sb.AppendLine($"                => handler.HandleAsync({handlerInvocation}));");
        sb.AppendLine();

        // Apply optional customizer
        var customizerImpl = customizers.FirstOrDefault(c => c.BaseName == TypeMapper.RegistrationClassName(operation.OperationId));
        if (customizerImpl is not null)
        {
            sb.AppendLine($"        var {varName}Customizer = services.GetService<{customizerClass}>();");
            sb.AppendLine($"        {varName}Customizer?.Configure({varName});");
            sb.AppendLine();
        }

        // Apply contract metadata
        sb.Append($"        {varName}");
        sb.AppendLine();
        sb.AppendLine($"            .WithName(\"{operation.OperationId}\")");

        if (!string.IsNullOrEmpty(operation.Summary))
            sb.AppendLine($"            .WithSummary(\"{EscapeString(operation.Summary!)}\")");

        if (!string.IsNullOrEmpty(operation.Description))
            sb.AppendLine($"            .WithDescription(\"{EscapeString(operation.Description!)}\")");

        if (operation.Tags.Count > 0)
        {
            var tags = string.Join(", ", operation.Tags.Select(t => $"\"{EscapeString(t)}\""));
            sb.AppendLine($"            .WithTags({tags})");
        }

        var responses = operation.Responses.OrderBy(r => r.StatusCode).ToList();
        for (var i = 0; i < responses.Count; i++)
        {
            var response = responses[i];
            var sep = i < responses.Count - 1 ? "" : ";";
            var responseTypeName = GetMetadataResponseTypeName(response, contractsNs, inlineResolver);
            var statusCodeExpression = TypeMapper.GetStatusCodeExpression(response.StatusCode);
            if (responseTypeName is not null && responseTypeName != "object")
            {
                if (TypeMapper.IsProblemResponse(response))
                {
                    sb.AppendLine($"            .Produces<{responseTypeName}>({statusCodeExpression}, \"application/problem+json\"){sep}");
                }
                else
                {
                    sb.AppendLine($"            .Produces<{responseTypeName}>({statusCodeExpression}){sep}");
                }
            }
            else
            {
                if (TypeMapper.IsProblemResponse(response))
                {
                    sb.AppendLine($"            .Produces({statusCodeExpression}, contentType: \"application/problem+json\"){sep}");
                }
                else
                {
                    sb.AppendLine($"            .Produces({statusCodeExpression}){sep}");
                }
            }
        }

        if (responses.Count == 0)
        {
            sb.AppendLine("            ;");
        }
    }

    private static string BuildLambdaParams(
        OpenApiOperation operation,
        string handlerClass,
        string contractsNs,
        InlineSchemaResolver? inlineResolver = null)
    {
        var parts = new List<string>();

        foreach (var p in operation.Parameters.Where(p => p.Location == ParameterLocation.Path))
            parts.Add($"{TypeMapper.MapSchema(p.Schema)} {TypeMapper.ToCamelCase(p.Name)}");

        if (operation.Parameters.Any(p => p.Location != ParameterLocation.Path))
            parts.Add($"[global::Microsoft.AspNetCore.Http.AsParameters] global::{handlerClass}.Parameters parameters");

        if (operation.RequestBody?.Schema is not null)
            parts.Add($"{TypeMapper.MapSchema(operation.RequestBody.Schema, contractsNamespace: contractsNs, resolveInline: inlineResolver)} request");

        parts.Add($"{handlerClass} handler");
        parts.Add("global::System.Threading.CancellationToken ct");

        return string.Join(",\n            ", parts);
    }

    private static string BuildHandlerInvocation(OpenApiOperation operation)
    {
        var args = new List<string>();

        foreach (var p in operation.Parameters.Where(p => p.Location == ParameterLocation.Path))
            args.Add(TypeMapper.ToCamelCase(p.Name));

        if (operation.Parameters.Any(p => p.Location != ParameterLocation.Path))
            args.Add("parameters");

        if (operation.RequestBody?.Schema is not null)
            args.Add("request");

        args.Add("ct");

        return string.Join(", ", args);
    }

    private static string? GetMetadataResponseTypeName(
        OpenApiResponse response,
        string contractsNs,
        InlineSchemaResolver? inlineResolver = null)
    {
        if (response.Schema is not null)
            return TypeMapper.MapSchema(response.Schema, contractsNamespace: contractsNs, resolveInline: inlineResolver);

        if (TypeMapper.IsProblemResponse(response))
            return "global::Microsoft.AspNetCore.Mvc.ProblemDetails";

        return null;
    }

    private static string EscapeString(string value)
        => value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\r\n", " ")
            .Replace("\n", " ")
            .Replace("\r", " ")
            .Replace("\t", " ");
}
