using System.Text;

using MinimalOpenAPI.Abstractions.Models;

namespace MinimalOpenAPI.Generator.CodeGen;

/// <summary>
/// Generates optional abstract endpoint configuration base classes.
/// </summary>
internal static class EndpointConfigurationGenerator
{
    /// <summary>Generates the endpoint configuration base type for an operation.</summary>
    public static string Generate(OpenApiOperation operation, string rootNamespace, string specName)
    {
        var configurationBaseClass = TypeMapper.EndpointConfigurationBaseClassName(operation.OperationId);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {rootNamespace}.{specName}.Endpoints;");
        sb.AppendLine();
        sb.AppendLine($"/// <summary>Optional endpoint configuration base for the <c>{operation.OperationId}</c> operation.</summary>");
        TypeMapper.AppendGeneratedAttributes(sb);
        sb.AppendLine($"public abstract class {configurationBaseClass}");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Applies application-specific endpoint configuration after contract-derived metadata.</summary>");
        sb.AppendLine("    public abstract void Configure(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder endpoint);");
        sb.AppendLine("}");
        return sb.ToString();
    }
}