using System.Text;

using MinimalOpenAPI.Abstractions.Models;

namespace MinimalOpenAPI.Generator.CodeGen;

/// <summary>
/// Generates abstract handler base classes for each operation.
/// Inline object schemas (those without a <c>$ref</c>) in <c>requestBody</c> or
/// <c>responses</c> are emitted as nested <c>sealed record</c> types inside the base
/// class instead of as top-level types in the Contracts namespace.
/// </summary>
internal static class HandlerBaseGenerator
{
    public static string Generate(
        OpenApiOperation operation,
        string rootNamespace,
        string specName,
        SchemaDirectionalityAnalysis directionality,
        IReadOnlyDictionary<string, OpenApiSchema>? allSchemas = null,
        List<AllOfPropertyConflict>? allOfConflicts = null)
    {
        var contractsNs = $"{rootNamespace}.{specName}.Contracts";
        var handlerClass = TypeMapper.HandlerClassName(operation.OperationId);
        var schemas = allSchemas ?? new Dictionary<string, OpenApiSchema>();

        // When the caller does not supply a collector, use a local discard list so that
        // AllOfSchemaFlattener.Resolve always has a valid target.  Callers that care about
        // conflicts (e.g. the source-generator orchestrator) should pass their own list.
        var conflictSink = allOfConflicts ?? [];

        // Collect inline schemas in deterministic order: request body first,
        // then responses ordered by status code.
        // For allOf schemas, also pre-compute the flattened (effective) shape so that the
        // nested record contains all merged properties, not just the raw allOf list.
        var inlineSchemas = new List<(OpenApiSchema OriginalSchema, OpenApiSchema EffectiveSchema, string TypeName, SchemaGenerationScope Scope)>();
        if (operation.RequestBody?.Schema is { } reqSchema && TypeMapper.IsInlineObject(reqSchema)
            && TypeMapper.ShouldGenerateJsonBody(operation.RequestBody))
        {
            var effective = reqSchema.AllOf.Count > 0
                ? AllOfSchemaFlattener.Resolve(reqSchema, schemas, TypeMapper.GetInlineRequestBodyTypeName(), conflictSink)
                : reqSchema;
            inlineSchemas.Add((reqSchema, effective, TypeMapper.GetInlineRequestBodyTypeName(), SchemaGenerationScope.Request));
        }
        foreach (var r in operation.Responses.OrderBy(r => r.StatusCode))
        {
            if (r.Schema is { } respSchema && TypeMapper.IsInlineObject(respSchema))
            {
                var typeName = TypeMapper.GetInlineResponseTypeName(r.StatusCode);
                var effective = respSchema.AllOf.Count > 0
                    ? AllOfSchemaFlattener.Resolve(respSchema, schemas, typeName, conflictSink)
                    : respSchema;
                inlineSchemas.Add((respSchema, effective, typeName, SchemaGenerationScope.Response));
            }
        }

        // Recursively collect all nested inline object schemas (including dictionary
        // value types and array item schemas) from the flattened effective schemas.  The list is ordered so that
        // dependencies appear before the schemas that reference them, which matches the
        // emission order required for the nested record declarations.
        var nestedSchemas = new List<(OpenApiSchema Schema, string TypeName, SchemaGenerationScope Scope)>();
        foreach (var (_, effective, typeName, scope) in inlineSchemas)
            CollectNestedInlineSchemas(effective, typeName, scope, directionality, nestedSchemas);

        // The resolver maps each schema instance (as it appears in the effective/original schema
        // graphs) to its short nested type name so that TypeMapper.MapSchema can substitute inline
        // schemas by reference when building property types, return types, and handler parameters.
        var allInlineSchemas = nestedSchemas
            .Concat(inlineSchemas.Select(s => (s.OriginalSchema, s.TypeName, s.Scope)))
            .ToList();

        // Resolver: inline schema → SHORT nested type name (usable inside the class body).
        InlineSchemaResolver localResolver = s =>
        {
            foreach (var (schema, typeName, _) in allInlineSchemas)
                if (ReferenceEquals(schema, s)) return typeName;
            return null;
        };

        var returnType = TypeMapper.BuildReturnType(
            operation.Responses,
            contractsNs,
            localResolver,
            resolveReference: referenceName => directionality.ResolveSchemaReference(referenceName, SchemaGenerationScope.Response));
        var parameters = BuildHandlerParameters(operation, contractsNs, localResolver, directionality);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {rootNamespace}.{specName}.Endpoints;");
        sb.AppendLine();
        sb.AppendLine($"/// <summary>Abstract handler base for the <c>{operation.OperationId}</c> operation.</summary>");
        TypeMapper.AppendGeneratedAttributes(sb);
        sb.AppendLine($"public class {handlerClass}");
        sb.AppendLine("{");

        // Emit the multipart form-data Request record when applicable.
        if (TypeMapper.ShouldGenerateMultipartFormBody(operation.RequestBody))
        {
            AppendMultipartFormRecord(sb, TypeMapper.GetInlineRequestBodyTypeName(), operation.RequestBody!.Schema!, directionality);
            sb.AppendLine();
        }

        // Emit all nested records (deepest dependencies first so each type is declared before
        // it is referenced by a parent record).
        foreach (var (schema, typeName, scope) in nestedSchemas)
        {
            AppendNestedRecord(sb, typeName, schema, contractsNs, directionality, scope, localResolver);
            sb.AppendLine();
        }

        // Emit nested records using the EFFECTIVE (flattened) schema so all merged properties
        // from allOf branches are included in the generated record.
        foreach (var (_, effective, typeName, scope) in inlineSchemas)
        {
            AppendNestedRecord(sb, typeName, effective, contractsNs, directionality, scope, localResolver);
            sb.AppendLine();
        }

        // Emit the Parameters nested record for non-path parameters (query, header, cookie).
        var nonPathParams = operation.Parameters
            .Where(p => p.Location != ParameterLocation.Path)
            .ToList();
        if (nonPathParams.Count > 0)
        {
            AppendParametersRecord(sb, nonPathParams, contractsNs);
            sb.AppendLine();
        }

        var problemResponses = operation.Responses
            .Where(TypeMapper.IsProblemResponse)
            .OrderBy(r => r.StatusCode)
            .ToList();

        foreach (var response in problemResponses)
        {
            AppendProblemResultWrapper(sb, response, contractsNs, localResolver);
            sb.AppendLine();
        }

        sb.Append($"    public virtual global::System.Threading.Tasks.Task<{returnType}> HandleAsync(");

        for (var i = 0; i < parameters.Count; i++)
        {
            var sep = i < parameters.Count - 1 ? ", " : "";
            sb.Append($"{parameters[i]}{sep}");
        }

        sb.AppendLine(")");
        sb.AppendLine($"        => throw new global::System.NotImplementedException(");
        sb.AppendLine($"            $\"{{GetType().Name}} has not implemented HandleAsync for operation '{operation.OperationId}'.\");");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static List<string> BuildHandlerParameters(
        OpenApiOperation operation,
        string contractsNs,
        InlineSchemaResolver localResolver,
        SchemaDirectionalityAnalysis directionality)
    {
        var list = new List<string>();

        // Path parameters first
        foreach (var p in operation.Parameters.Where(p => p.Location == ParameterLocation.Path))
        {
            list.Add($"{TypeMapper.MapSchema(p.Schema)} {TypeMapper.ToCamelCase(p.Name)}");
        }

        // Non-path parameters (query, header, cookie) wrapped in Parameters record
        if (operation.Parameters.Any(p => p.Location != ParameterLocation.Path))
        {
            list.Add("Parameters parameters");
        }

        // Request body
        if (TypeMapper.ShouldGenerateJsonBody(operation.RequestBody))
        {
            var bodyType = TypeMapper.MapSchema(
                operation.RequestBody!.Schema!,
                contractsNamespace: contractsNs,
                resolveInline: localResolver,
                resolveReference: referenceName => directionality.ResolveSchemaReference(referenceName, SchemaGenerationScope.Request));
            list.Add($"{bodyType} request");
        }
        else if (TypeMapper.ShouldGenerateMultipartFormBody(operation.RequestBody))
        {
            list.Add($"{TypeMapper.GetInlineRequestBodyTypeName()} request");
        }

        // CancellationToken always last
        list.Add("global::System.Threading.CancellationToken cancellationToken");

        return list;
    }

    /// <summary>
    /// Recursively walks <paramref name="effectiveSchema"/> and collects every inline object
    /// and dictionary-value inline-object property, together with the derived C# type name each
    /// one will be emitted as. Items are added in dependency order: a nested type is added only
    /// after all of its own nested types have been added first, so the resulting list can be
    /// iterated in order to emit declarations without forward references.
    /// </summary>
    private static void CollectNestedInlineSchemas(
        OpenApiSchema effectiveSchema,
        string parentTypeName,
        SchemaGenerationScope scope,
        SchemaDirectionalityAnalysis directionality,
        List<(OpenApiSchema Schema, string TypeName, SchemaGenerationScope Scope)> collected)
    {
        foreach (var propKvp in effectiveSchema.Properties)
        {
            var propSchema = propKvp.Value;
            if (!directionality.ShouldIncludeProperty(propSchema, scope))
                continue;

            var derivedName = parentTypeName + TypeMapper.ToPascalCase(propKvp.Key);

            if (TypeMapper.IsInlineObject(propSchema))
            {
                // Recurse first so that deeper types are declared before this one.
                CollectNestedInlineSchemas(propSchema, derivedName, scope, directionality, collected);
                collected.Add((propSchema, derivedName, scope));
            }
            else if (TypeMapper.IsDictionarySchema(propSchema)
                && propSchema.AdditionalProperties is { } valueSchema
                && TypeMapper.IsInlineObject(valueSchema))
            {
                var valueName = derivedName + "Value";
                CollectNestedInlineSchemas(valueSchema, valueName, scope, directionality, collected);
                collected.Add((valueSchema, valueName, scope));
            }
            else if (propSchema.Type?.ToLowerInvariant() == "array" && propSchema.Items is { } itemSchema)
            {
                var itemName = derivedName + "Item";
                CollectArrayItemInlineSchemas(itemSchema, itemName, scope, directionality, collected);
            }
        }
    }

    /// <summary>
    /// Walks an array item schema and collects any inline object types it introduces.
    /// Only inline object item schemas are collected; inline enum item schemas are intentionally
    /// ignored so that operation-scoped inline enum array items fall back to the primitive
    /// <c>string[]</c> type until handler-local enum emission is implemented.
    /// When the item schema is itself an array, recurses into its own items so that
    /// arbitrary array nesting (e.g. <c>array.items.items.type = object</c>) is handled.
    /// </summary>
    private static void CollectArrayItemInlineSchemas(
        OpenApiSchema itemSchema,
        string itemName,
        SchemaGenerationScope scope,
        SchemaDirectionalityAnalysis directionality,
        List<(OpenApiSchema Schema, string TypeName, SchemaGenerationScope Scope)> collected)
    {
        if (TypeMapper.IsInlineObject(itemSchema))
        {
            // Recurse into the item schema first so its own nested types are declared
            // before the item type itself.
            CollectNestedInlineSchemas(itemSchema, itemName, scope, directionality, collected);
            collected.Add((itemSchema, itemName, scope));
        }
        else if (itemSchema.Type?.ToLowerInvariant() == "array" && itemSchema.Items is { } innerItemSchema)
        {
            // array-of-array: walk into the inner item schema using an extra "Item" suffix.
            CollectArrayItemInlineSchemas(innerItemSchema, itemName + "Item", scope, directionality, collected);
        }
    }

    /// <summary>Appends a nested <c>sealed record</c> for an inline schema.</summary>
    private static void AppendNestedRecord(
        StringBuilder sb,
        string typeName,
        OpenApiSchema schema,
        string contractsNamespace,
        SchemaDirectionalityAnalysis directionality,
        SchemaGenerationScope scope,
        InlineSchemaResolver? resolveInline = null)
    {
        sb.AppendLine($"    /// <summary>Inline DTO for the <c>{typeName}</c> schema of this operation.</summary>");
        TypeMapper.AppendGeneratedAttributes(sb, "    ");
        sb.AppendLine($"    public sealed record {typeName}");
        sb.AppendLine("    {");

        foreach (var propKvp in schema.Properties)
        {
            var propName = propKvp.Key;
            var propSchema = propKvp.Value;
            if (!directionality.ShouldIncludeProperty(propSchema, scope))
                continue;
            var isRequired = schema.Required.Contains(propName, StringComparer.OrdinalIgnoreCase);
            var nullable = propSchema.Nullable || !isRequired;
            var csharpTypeName = TypeMapper.MapSchema(
                propSchema,
                nullable: nullable,
                contractsNamespace: contractsNamespace,
                resolveInline: resolveInline,
                resolveReference: referenceName => directionality.ResolveSchemaReference(referenceName, scope));
            var csharpName = TypeMapper.ToPascalCase(propName);

            sb.AppendLine($"        [global::System.Text.Json.Serialization.JsonPropertyName(\"{propName}\")]");

            foreach (var attr in ValidationAttributeEmitter.GetAttributes(propSchema, "        "))
                sb.AppendLine(attr);

            if (nullable)
            {
                sb.AppendLine($"        public {csharpTypeName} {csharpName} {{ get; init; }}");
            }
            else
            {
                sb.AppendLine($"        public required {csharpTypeName} {csharpName} {{ get; init; }}");
            }
        }

        sb.AppendLine("    }");
    }

    /// <summary>
    /// Appends a nested <c>sealed record</c> for a <c>multipart/form-data</c> request body.
    /// Properties use <c>[global::Microsoft.AspNetCore.Mvc.FromForm(Name = "...")]</c> instead
    /// of <c>[JsonPropertyName]</c>, and file fields (<c>string/binary</c>) are mapped to
    /// <c>IFormFile</c> rather than <c>string</c>.
    /// </summary>
    private static void AppendMultipartFormRecord(
        StringBuilder sb,
        string typeName,
        OpenApiSchema schema,
        SchemaDirectionalityAnalysis directionality)
    {
        sb.AppendLine($"    /// <summary>Form data DTO for the <c>multipart/form-data</c> request body of this operation.</summary>");
        TypeMapper.AppendGeneratedAttributes(sb, "    ");
        sb.AppendLine($"    public sealed record {typeName}");
        sb.AppendLine("    {");

        foreach (var propKvp in schema.Properties)
        {
            var propName = propKvp.Key;
            var propSchema = propKvp.Value;
            if (!directionality.ShouldIncludeProperty(propSchema, SchemaGenerationScope.Request))
                continue;

            var isRequired = schema.Required.Contains(propName, StringComparer.OrdinalIgnoreCase);
            var nullable = propSchema.Nullable || !isRequired;
            var csharpTypeName = TypeMapper.MapFormFieldSchema(propSchema, nullable: nullable);
            var csharpName = TypeMapper.ToPascalCase(propName);

            sb.AppendLine($"        [global::Microsoft.AspNetCore.Mvc.FromForm(Name = \"{propName}\")]");

            if (isRequired)
                sb.AppendLine($"        public required {csharpTypeName} {csharpName} {{ get; init; }}");
            else
                sb.AppendLine($"        public {csharpTypeName} {csharpName} {{ get; init; }}");
        }

        sb.AppendLine("    }");
    }

    /// <summary>
    /// Appends the nested <c>Parameters</c> sealed record aggregating all non-path parameters
    /// (query, header and cookie) so they can be bound via <c>[AsParameters]</c> without
    /// breaking existing handler implementations when new optional parameters are added.
    /// </summary>
    private static void AppendParametersRecord(StringBuilder sb, List<OpenApiParameter> parameters, string contractsNamespace)
    {
        sb.AppendLine("    /// <summary>Aggregates all query, header and cookie parameters for this operation.</summary>");
        TypeMapper.AppendGeneratedAttributes(sb, "    ");
        sb.AppendLine("    public sealed record Parameters");
        sb.AppendLine("    {");

        foreach (var p in parameters)
        {
            var type = TypeMapper.MapSchema(p.Schema, nullable: !p.Required, contractsNamespace: contractsNamespace);
            var propName = TypeMapper.ToPascalCase(p.Name);
            var bindingAttr = GetBindingAttribute(p);
            if (bindingAttr is not null)
                sb.AppendLine($"        {bindingAttr}");
            foreach (var attr in ValidationAttributeEmitter.GetAttributes(p.Schema, "        "))
                sb.AppendLine(attr);
            var defaultInitializer = GetDefaultInitializer(p.Schema);
            if (defaultInitializer is not null)
                sb.AppendLine($"        public {type} {propName} {{ get; init; }} = {defaultInitializer};");
            else if (p.Required && !type.EndsWith("?"))
                sb.AppendLine($"        public {type} {propName} {{ get; init; }} = default!;");
            else
                sb.AppendLine($"        public {type} {propName} {{ get; init; }}");
        }

        sb.AppendLine("    }");
    }

    private static string? GetBindingAttribute(OpenApiParameter p) => p.Location switch
    {
        ParameterLocation.Query => $"[global::Microsoft.AspNetCore.Mvc.FromQuery(Name = \"{p.Name}\")]",
        ParameterLocation.Header => $"[global::Microsoft.AspNetCore.Mvc.FromHeader(Name = \"{p.Name}\")]",
        // Cookie parameters have no dedicated binding attribute in ASP.NET Core minimal APIs;
        // they are included in the Parameters record without auto-binding so that the handler
        // signature stays stable. Implementations can access cookie values via HttpContext.
        ParameterLocation.Cookie => null,
        _ => null
    };

    /// <summary>
    /// Returns a C# default-value expression for a parameter's <c>default</c> keyword, or
    /// <see langword="null"/> when the default cannot be safely represented as a literal.
    /// </summary>
    private static string? GetDefaultInitializer(OpenApiSchema schema)
    {
        if (schema.Default is null) return null;
        if (schema.Reference is not null) return null; // $ref parameters — skip

        var raw = schema.Default;
        var type = schema.Type?.ToLowerInvariant();
        var format = schema.Format?.ToLowerInvariant();

        if (type == "string")
        {
            if (format == "uuid")
            {
                return System.Guid.TryParse(raw, out var guid)
                    ? $"global::System.Guid.Parse(\"{guid}\")"
                    : null;
            }

            if (format == "date")
            {
                // Parse and validate the date strictly so the emitted initializer never throws.
                // DateTime.TryParseExact is available in netstandard2.0 (unlike DateOnly.TryParse);
                // we use it purely for validation and then emit a constructor call rather than
                // a Parse call so that the generated code itself is non-throwing.
                if (!System.DateTime.TryParseExact(
                        raw,
                        "yyyy-MM-dd",
                        System.Globalization.CultureInfo.InvariantCulture,
                        System.Globalization.DateTimeStyles.None,
                        out var dt))
                    return null;
                return $"new global::System.DateOnly({dt.Year}, {dt.Month}, {dt.Day})";
            }

            return $"\"{EscapeStringLiteral(raw)}\"";
        }

        if (type == "integer")
        {
            if (format == "int64")
                return long.TryParse(raw, out _) ? raw + "L" : null;
            return int.TryParse(raw, out _) ? raw : null;
        }

        if (type == "number")
        {
            if (!double.TryParse(raw, System.Globalization.NumberStyles.Any,
                    System.Globalization.CultureInfo.InvariantCulture, out var d))
                return null;

            if (format == "float")
                return FormatFloat((float)d);

            return FormatDouble(d);
        }

        if (type == "boolean")
        {
            if (raw.Equals("true", StringComparison.OrdinalIgnoreCase)) return "true";
            if (raw.Equals("false", StringComparison.OrdinalIgnoreCase)) return "false";
        }

        return null;
    }

    private static string EscapeStringLiteral(string value)
    {
        var sb = new StringBuilder(value.Length + 4);
        foreach (var c in value)
        {
            switch (c)
            {
                case '\\': sb.Append("\\\\"); break;
                case '"': sb.Append("\\\""); break;
                case '\n': sb.Append("\\n"); break;
                case '\r': sb.Append("\\r"); break;
                case '\t': sb.Append("\\t"); break;
                default:
                    if (char.IsControl(c))
                        sb.Append($"\\u{(int)c:x4}");
                    else
                        sb.Append(c);
                    break;
            }
        }
        return sb.ToString();
    }

    private static string FormatFloat(float value)
    {
        if (value == (float)Math.Floor(value))
            return ((long)value).ToString(System.Globalization.CultureInfo.InvariantCulture) + "f";
        return value.ToString("R", System.Globalization.CultureInfo.InvariantCulture) + "f";
    }

    private static string FormatDouble(double value)
    {
        if (value == Math.Floor(value)
            && value > (double)long.MinValue
            && value < (double)long.MaxValue)
        {
            return ((long)value).ToString(System.Globalization.CultureInfo.InvariantCulture) + ".0";
        }
        return value.ToString("R", System.Globalization.CultureInfo.InvariantCulture);
    }

    private static void AppendProblemResultWrapper(
        StringBuilder sb,
        OpenApiResponse response,
        string contractsNamespace,
        InlineSchemaResolver? resolveInline = null)
    {
        var payloadType = response.Schema is not null
            ? TypeMapper.MapSchema(response.Schema, contractsNamespace: contractsNamespace, resolveInline: resolveInline)
            : "global::Microsoft.AspNetCore.Mvc.ProblemDetails";
        var resultTypeName = TypeMapper.GetProblemResultTypeName(response.StatusCode);
        var statusCodeExpression = TypeMapper.GetStatusCodeExpression(response.StatusCode);

        sb.AppendLine($"    /// <summary>Typed <c>application/problem+json</c> result for HTTP {response.StatusCode}.</summary>");
        TypeMapper.AppendGeneratedAttributes(sb, "    ");
        sb.AppendLine(
            $"    public sealed class {resultTypeName} : global::Microsoft.AspNetCore.Http.IResult, global::Microsoft.AspNetCore.Http.IStatusCodeHttpResult, global::Microsoft.AspNetCore.Http.IValueHttpResult, global::Microsoft.AspNetCore.Http.IValueHttpResult<{payloadType}>");
        sb.AppendLine("    {");
        sb.AppendLine($"        public {resultTypeName}({payloadType} value)");
        sb.AppendLine("        {");
        sb.AppendLine("            Value = value;");
        if (response.Schema is null)
        {
            sb.AppendLine(
                $"            Value.Status ??= {statusCodeExpression};");
        }
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine($"        public int? StatusCode => {statusCodeExpression};");
        sb.AppendLine();
        sb.AppendLine("        object? global::Microsoft.AspNetCore.Http.IValueHttpResult.Value => Value;");
        sb.AppendLine();
        sb.AppendLine($"        public {payloadType} Value {{ get; }}");
        sb.AppendLine();
        sb.AppendLine("        public global::System.Threading.Tasks.Task ExecuteAsync(global::Microsoft.AspNetCore.Http.HttpContext httpContext)");
        sb.AppendLine("        {");
        sb.AppendLine($"            httpContext.Response.StatusCode = {statusCodeExpression};");
        sb.AppendLine();
        sb.AppendLine("            return global::Microsoft.AspNetCore.Http.HttpResponseJsonExtensions.WriteAsJsonAsync(");
        sb.AppendLine("                httpContext.Response,");
        sb.AppendLine("                Value,");
        sb.AppendLine("                options: null,");
        sb.AppendLine("                contentType: \"application/problem+json\");");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
    }
}