using MinimalOpenAPI.Abstractions.Models;
using System.Text;

namespace MinimalOpenAPI.Generator.CodeGen;

/// <summary>
/// Generates the DI registration extension method for all discovered handlers.
/// </summary>
internal static class DependencyInjectionRegistrationGenerator
{
    public static string Generate(
        List<OpenApiOperation> operations,
        List<DiscoveredImplementation> handlers,
        List<DiscoveredImplementation> customizers,
        string rootNamespace)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using global::Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine($"namespace {rootNamespace}.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>Generated DI registration for MinimalOpenAPI handlers.</summary>");
        TypeMapper.AppendGeneratedAttributes(sb);
        sb.AppendLine("public static class MinimalOpenApiGeneratedServiceCollectionExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Registers all MinimalOpenAPI services, endpoint handlers, and registration customizers.</summary>");
        sb.AppendLine("    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddMinimalOpenApi(");
        sb.AppendLine("        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine("    {");

        foreach (var op in operations)
        {
            var handlerBase = TypeMapper.HandlerClassName(op.OperationId);
            var handlerImpl = handlers.FirstOrDefault(h => h.BaseName == handlerBase);
            if (handlerImpl is not null)
            {
                sb.AppendLine($"        services.AddScoped<{rootNamespace}.Generated.{handlerBase}, {handlerImpl.FullName}>();");
            }

            var customizerBase = TypeMapper.RegistrationClassName(op.OperationId);
            var customizerImpl = customizers.FirstOrDefault(c => c.BaseName == customizerBase);
            if (customizerImpl is not null)
            {
                sb.AppendLine($"        services.AddSingleton<{rootNamespace}.Generated.{customizerBase}, {customizerImpl.FullName}>();");
            }
        }

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }
}

/// <summary>Represents a discovered concrete implementation of a generated base class.</summary>
internal sealed class DiscoveredImplementation
{
    public string BaseName { get; init; } = string.Empty;
    public string FullName { get; init; } = string.Empty;
}
