using MinimalOpenAPI.Abstractions.Models;
using System.Text;

namespace MinimalOpenAPI.Generator.CodeGen;

/// <summary>
/// Generates sealed record DTOs from OpenAPI component schemas.
/// </summary>
internal static class DtoGenerator
{
    public static string Generate(
        Dictionary<string, OpenApiSchema> schemas,
        string rootNamespace)
    {
        if (schemas.Count == 0) return string.Empty;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {rootNamespace}.Generated;");
        sb.AppendLine();

        foreach (var kvp in schemas)
        {
            var name = kvp.Key;
            var schema = kvp.Value;
            if (schema.Type != "object" && schema.Ref is null && schema.Properties.Count == 0)
                continue;

            GenerateRecord(sb, name, schema, schemas);
            sb.AppendLine();
        }

        return sb.ToString();
    }

    private static void GenerateRecord(
        StringBuilder sb,
        string name,
        OpenApiSchema schema,
        Dictionary<string, OpenApiSchema> allSchemas)
    {
        sb.AppendLine($"/// <summary>Generated DTO for schema <c>{name}</c>.</summary>");
        TypeMapper.AppendGeneratedAttributes(sb);
        sb.Append($"public sealed record {name}(");

        var props = schema.Properties.ToList();
        if (props.Count == 0)
        {
            sb.AppendLine(");");
            return;
        }

        sb.AppendLine();
        for (var i = 0; i < props.Count; i++)
        {
            var propKvp = props[i];
            var propName = propKvp.Key;
            var propSchema = propKvp.Value;
            var isRequired = schema.Required.Contains(propName, StringComparer.OrdinalIgnoreCase);
            var nullable = propSchema.Nullable || !isRequired;
            var typeName = TypeMapper.MapSchema(propSchema, nullable: nullable);
            var csharpName = TypeMapper.ToPascalCase(propName);
            var sep = i < props.Count - 1 ? "," : "";
            sb.AppendLine($"    {typeName} {csharpName}{sep}");
        }

        sb.AppendLine(");");
    }
}
