using MinimalOpenAPI.Abstractions.Models;
using System.Text;

namespace MinimalOpenAPI.Generator.CodeGen;

/// <summary>
/// Generates sealed record DTOs from OpenAPI component schemas.
/// </summary>
internal static class DtoGenerator
{
    public static string Generate(
        Dictionary<string, OpenApiSchema> schemas,
        string rootNamespace)
    {
        if (schemas.Count == 0) return string.Empty;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using global::System.Text.Json.Serialization;");
        sb.AppendLine();
        sb.AppendLine($"namespace {rootNamespace}.Generated;");
        sb.AppendLine();

        foreach (var kvp in schemas)
        {
            var name = kvp.Key;
            var schema = kvp.Value;
            if (schema.Type != "object" && schema.Ref is null && schema.Properties.Count == 0)
                continue;

            GenerateRecord(sb, name, schema, schemas);
            sb.AppendLine();
        }

        return sb.ToString();
    }

    private static void GenerateRecord(
        StringBuilder sb,
        string name,
        OpenApiSchema schema,
        Dictionary<string, OpenApiSchema> allSchemas)
    {
        sb.AppendLine($"/// <summary>Generated DTO for schema <c>{name}</c>.</summary>");
        TypeMapper.AppendGeneratedAttributes(sb);
        sb.AppendLine($"public sealed record {name}");
        sb.AppendLine("{");

        foreach (var propKvp in schema.Properties)
        {
            var propName = propKvp.Key;
            var propSchema = propKvp.Value;
            var isRequired = schema.Required.Contains(propName, StringComparer.OrdinalIgnoreCase);
            var nullable = propSchema.Nullable || !isRequired;
            var typeName = TypeMapper.MapSchema(propSchema, nullable: nullable);
            var csharpName = TypeMapper.ToPascalCase(propName);

            sb.AppendLine($"    [JsonPropertyName(\"{propName}\")]");

            if (nullable)
            {
                sb.AppendLine($"    public {typeName} {csharpName} {{ get; init; }}");
            }
            else
            {
                var defaultValue = GetDefaultValue(typeName);
                sb.AppendLine($"    public {typeName} {csharpName} {{ get; init; }} = {defaultValue};");
            }
        }

        sb.AppendLine("}");
    }

    private static string GetDefaultValue(string typeName) => typeName switch
    {
        "string" => "string.Empty",
        "bool" => "false",
        "int" => "0",
        "long" => "0",
        "float" => "0f",
        "double" => "0.0",
        "global::System.Guid" => "global::System.Guid.Empty",
        "global::System.DateTimeOffset" => "default",
        _ => "default!"
    };
}
