using MinimalOpenAPI.Generator.Models;
using System.Text;

namespace MinimalOpenAPI.Generator.CodeGen;

/// <summary>
/// Generates the MapEndpoints extension method that maps all operations.
/// </summary>
internal static class EndpointMappingGenerator
{
    public static string Generate(
        List<OpenApiOperation> operations,
        List<DiscoveredImplementation> customizers,
        string rootNamespace)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using global::Microsoft.AspNetCore.Http;");
        sb.AppendLine("using global::Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine($"namespace {rootNamespace}.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>Generated endpoint route builder extensions for MinimalOpenAPI.</summary>");
        sb.AppendLine("public static class MinimalOpenApiGeneratedEndpointRouteBuilderExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Maps all generated MinimalOpenAPI endpoints.</summary>");
        sb.AppendLine("    public static global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder MapEndpoints(");
        sb.AppendLine("        this global::Microsoft.AspNetCore.Routing.IEndpointRouteBuilder builder)");
        sb.AppendLine("    {");
        sb.AppendLine("        var services = builder.ServiceProvider;");
        sb.AppendLine();

        foreach (var op in operations)
        {
            GenerateEndpointMapping(sb, op, customizers, rootNamespace);
            sb.AppendLine();
        }

        sb.AppendLine("        return builder;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void GenerateEndpointMapping(
        StringBuilder sb,
        OpenApiOperation operation,
        List<DiscoveredImplementation> customizers,
        string rootNamespace)
    {
        var handlerClass = $"{rootNamespace}.Generated.{TypeMapper.HandlerClassName(operation.OperationId)}";
        var customizerClass = $"{rootNamespace}.Generated.{TypeMapper.RegistrationClassName(operation.OperationId)}";
        var constrainedRoute = TypeMapper.BuildConstrainedRoute(operation.Route, operation.Parameters);
        var lambdaParams = BuildLambdaParams(operation, handlerClass);
        var handlerInvocation = BuildHandlerInvocation(operation);
        var httpMethod = TypeMapper.ToPascalCase(operation.HttpMethod.ToLowerInvariant());
        var varName = TypeMapper.ToCamelCase(TypeMapper.HandlerClassName(operation.OperationId));

        sb.AppendLine($"        // {operation.OperationId}");
        sb.AppendLine($"        var {varName} = builder.Map{httpMethod}(");
        sb.AppendLine($"            \"{constrainedRoute}\",");
        sb.AppendLine($"            static ({lambdaParams})");
        sb.AppendLine($"                => handler.Handle({handlerInvocation}));");
        sb.AppendLine();

        // Apply optional customizer
        var customizerImpl = customizers.FirstOrDefault(c => c.BaseName == TypeMapper.RegistrationClassName(operation.OperationId));
        if (customizerImpl is not null)
        {
            sb.AppendLine($"        var {varName}Customizer = services.GetService<{customizerClass}>();");
            sb.AppendLine($"        {varName}Customizer?.Configure({varName});");
            sb.AppendLine();
        }

        // Apply contract metadata
        sb.Append($"        {varName}");
        sb.AppendLine();
        sb.AppendLine($"            .WithName(\"{operation.OperationId}\")");

        var responses = operation.Responses.OrderBy(r => r.StatusCode).ToList();
        for (var i = 0; i < responses.Count; i++)
        {
            var response = responses[i];
            var sep = i < responses.Count - 1 ? "" : ";";
            if (response.Schema?.Ref is not null)
            {
                sb.AppendLine($"            .Produces<{response.Schema.Ref}>(global::Microsoft.AspNetCore.Http.StatusCodes.Status{response.StatusCode}{GetStatusCodeName(response.StatusCode)}){sep}");
            }
            else
            {
                sb.AppendLine($"            .Produces(global::Microsoft.AspNetCore.Http.StatusCodes.Status{response.StatusCode}{GetStatusCodeName(response.StatusCode)}){sep}");
            }
        }

        if (responses.Count == 0)
        {
            sb.AppendLine("            ;");
        }
    }

    private static string BuildLambdaParams(OpenApiOperation operation, string handlerClass)
    {
        var parts = new List<string>();

        foreach (var p in operation.Parameters.Where(p => p.In == ParameterLocation.Path))
            parts.Add($"{TypeMapper.MapSchema(p.Schema)} {TypeMapper.ToCamelCase(p.Name)}");

        foreach (var p in operation.Parameters.Where(p => p.In == ParameterLocation.Query))
        {
            var type = TypeMapper.MapSchema(p.Schema, nullable: !p.Required);
            parts.Add($"{type} {TypeMapper.ToCamelCase(p.Name)}");
        }

        if (operation.RequestBody?.Schema is not null)
            parts.Add($"{TypeMapper.MapSchema(operation.RequestBody.Schema)} request");

        parts.Add($"{handlerClass} handler");
        parts.Add("global::System.Threading.CancellationToken ct");

        return string.Join(",\n            ", parts);
    }

    private static string BuildHandlerInvocation(OpenApiOperation operation)
    {
        var args = new List<string>();

        foreach (var p in operation.Parameters.Where(p => p.In == ParameterLocation.Path))
            args.Add(TypeMapper.ToCamelCase(p.Name));

        foreach (var p in operation.Parameters.Where(p => p.In == ParameterLocation.Query))
            args.Add(TypeMapper.ToCamelCase(p.Name));

        if (operation.RequestBody?.Schema is not null)
            args.Add("request");

        args.Add("ct");

        return string.Join(", ", args);
    }

    private static string GetStatusCodeName(int code) => code switch
    {
        200 => "OK",
        201 => "Created",
        202 => "Accepted",
        204 => "NoContent",
        400 => "BadRequest",
        401 => "Unauthorized",
        403 => "Forbidden",
        404 => "NotFound",
        409 => "Conflict",
        422 => "UnprocessableEntity",
        500 => "InternalServerError",
        _ => string.Empty
    };
}
