using MinimalOpenAPI.Abstractions.Models;
using System.Text;

namespace MinimalOpenAPI.Generator.CodeGen;

/// <summary>
/// Generates abstract handler base classes for each operation.
/// </summary>
internal static class HandlerBaseGenerator
{
    public static string Generate(OpenApiOperation operation, string rootNamespace)
    {
        var contractsNs = $"{rootNamespace}.Contracts";
        var handlerClass = TypeMapper.HandlerClassName(operation.OperationId);
        var returnType = TypeMapper.BuildReturnType(operation.Responses, contractsNs);
        var parameters = BuildHandlerParameters(operation, contractsNs);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {rootNamespace}.Endpoints;");
        sb.AppendLine();
        sb.AppendLine($"/// <summary>Abstract handler base for the <c>{operation.OperationId}</c> operation.</summary>");
        TypeMapper.AppendGeneratedAttributes(sb);
        sb.AppendLine($"public class {handlerClass}");
        sb.AppendLine("{");
        sb.Append($"    public virtual global::System.Threading.Tasks.Task<{returnType}> HandleAsync(");

        for (var i = 0; i < parameters.Count; i++)
        {
            var sep = i < parameters.Count - 1 ? ", " : "";
            sb.Append($"{parameters[i]}{sep}");
        }

        sb.AppendLine(")");
        sb.AppendLine($"        => throw new global::System.NotImplementedException(");
        sb.AppendLine($"            $\"{{GetType().Name}} has not implemented HandleAsync for operation '{operation.OperationId}'.\");");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static List<string> BuildHandlerParameters(OpenApiOperation operation, string contractsNs)
    {
        var list = new List<string>();

        // Path parameters first
        foreach (var p in operation.Parameters.Where(p => p.In == ParameterLocation.Path))
        {
            list.Add($"{TypeMapper.MapSchema(p.Schema)} {TypeMapper.ToCamelCase(p.Name)}");
        }

        // Query parameters
        foreach (var p in operation.Parameters.Where(p => p.In == ParameterLocation.Query))
        {
            var type = TypeMapper.MapSchema(p.Schema, nullable: !p.Required);
            list.Add($"{type} {TypeMapper.ToCamelCase(p.Name)}");
        }

        // Request body
        if (operation.RequestBody?.Schema is not null)
        {
            var bodyType = TypeMapper.MapSchema(operation.RequestBody.Schema, contractsNamespace: contractsNs);
            list.Add($"{bodyType} request");
        }

        // CancellationToken always last
        list.Add("global::System.Threading.CancellationToken cancellationToken");

        return list;
    }
}
