using MinimalOpenAPI.Abstractions.Models;
using System.Text;

namespace MinimalOpenAPI.Generator.CodeGen;

/// <summary>
/// Generates abstract handler base classes for each operation.
/// Inline object schemas (those without a <c>$ref</c>) in <c>requestBody</c> or
/// <c>responses</c> are emitted as nested <c>sealed record</c> types inside the base
/// class instead of as top-level types in the Contracts namespace.
/// </summary>
internal static class HandlerBaseGenerator
{
    public static string Generate(OpenApiOperation operation, string rootNamespace)
    {
        var contractsNs = $"{rootNamespace}.Contracts";
        var handlerClass = TypeMapper.HandlerClassName(operation.OperationId);

        // Collect inline schemas in deterministic order: request body first,
        // then responses ordered by status code.
        var inlineSchemas = new List<(OpenApiSchema Schema, string TypeName)>();
        if (operation.RequestBody?.Schema is { } reqSchema && TypeMapper.IsInlineObject(reqSchema))
            inlineSchemas.Add((reqSchema, TypeMapper.GetInlineRequestBodyTypeName()));
        foreach (var r in operation.Responses.OrderBy(r => r.StatusCode))
        {
            if (r.Schema is { } respSchema && TypeMapper.IsInlineObject(respSchema))
                inlineSchemas.Add((respSchema, TypeMapper.GetInlineResponseTypeName(r.StatusCode)));
        }

        // Resolver: inline schema → SHORT nested type name (usable inside the class body).
        InlineSchemaResolver localResolver = s =>
        {
            foreach (var (schema, typeName) in inlineSchemas)
                if (ReferenceEquals(schema, s)) return typeName;
            return null;
        };

        var returnType = TypeMapper.BuildReturnType(operation.Responses, contractsNs, localResolver);
        var parameters = BuildHandlerParameters(operation, contractsNs, localResolver);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {rootNamespace}.Endpoints;");
        sb.AppendLine();
        sb.AppendLine($"/// <summary>Abstract handler base for the <c>{operation.OperationId}</c> operation.</summary>");
        TypeMapper.AppendGeneratedAttributes(sb);
        sb.AppendLine($"public class {handlerClass}");
        sb.AppendLine("{");

        // Emit one nested record per inline schema before the handler method.
        foreach (var (schema, typeName) in inlineSchemas)
        {
            AppendNestedRecord(sb, typeName, schema);
            sb.AppendLine();
        }

        sb.Append($"    public virtual global::System.Threading.Tasks.Task<{returnType}> HandleAsync(");

        for (var i = 0; i < parameters.Count; i++)
        {
            var sep = i < parameters.Count - 1 ? ", " : "";
            sb.Append($"{parameters[i]}{sep}");
        }

        sb.AppendLine(")");
        sb.AppendLine($"        => throw new global::System.NotImplementedException(");
        sb.AppendLine($"            $\"{{GetType().Name}} has not implemented HandleAsync for operation '{operation.OperationId}'.\");");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static List<string> BuildHandlerParameters(
        OpenApiOperation operation,
        string contractsNs,
        InlineSchemaResolver localResolver)
    {
        var list = new List<string>();

        // Path parameters first
        foreach (var p in operation.Parameters.Where(p => p.In == ParameterLocation.Path))
        {
            list.Add($"{TypeMapper.MapSchema(p.Schema)} {TypeMapper.ToCamelCase(p.Name)}");
        }

        // Query parameters
        foreach (var p in operation.Parameters.Where(p => p.In == ParameterLocation.Query))
        {
            var type = TypeMapper.MapSchema(p.Schema, nullable: !p.Required);
            list.Add($"{type} {TypeMapper.ToCamelCase(p.Name)}");
        }

        // Request body
        if (operation.RequestBody?.Schema is not null)
        {
            var bodyType = TypeMapper.MapSchema(
                operation.RequestBody.Schema,
                contractsNamespace: contractsNs,
                resolveInline: localResolver);
            list.Add($"{bodyType} request");
        }

        // CancellationToken always last
        list.Add("global::System.Threading.CancellationToken cancellationToken");

        return list;
    }

    /// <summary>Appends a nested <c>sealed record</c> for an inline schema.</summary>
    private static void AppendNestedRecord(StringBuilder sb, string typeName, OpenApiSchema schema)
    {
        sb.AppendLine($"    /// <summary>Inline DTO for the <c>{typeName}</c> schema of this operation.</summary>");
        TypeMapper.AppendGeneratedAttributes(sb, "    ");
        sb.AppendLine($"    public sealed record {typeName}");
        sb.AppendLine("    {");

        foreach (var propKvp in schema.Properties)
        {
            var propName = propKvp.Key;
            var propSchema = propKvp.Value;
            var isRequired = schema.Required.Contains(propName, StringComparer.OrdinalIgnoreCase);
            var nullable = propSchema.Nullable || !isRequired;
            var csharpTypeName = TypeMapper.MapSchema(propSchema, nullable: nullable);
            var csharpName = TypeMapper.ToPascalCase(propName);

            sb.AppendLine($"        [global::System.Text.Json.Serialization.JsonPropertyName(\"{propName}\")]");

            if (nullable)
            {
                sb.AppendLine($"        public {csharpTypeName} {csharpName} {{ get; init; }}");
            }
            else
            {
                var defaultValue = TypeMapper.GetDefaultValue(csharpTypeName);
                sb.AppendLine($"        public {csharpTypeName} {csharpName} {{ get; init; }} = {defaultValue};");
            }
        }

        sb.AppendLine("    }");
    }
}
