using MinimalOpenAPI.Abstractions.Models;
using System.Text;

namespace MinimalOpenAPI.Generator.CodeGen;

/// <summary>
/// Generates optional abstract registration customizer base classes.
/// </summary>
internal static class RegistrationCustomizerGenerator
{
    public static string Generate(OpenApiOperation operation, string rootNamespace)
    {
        var registrationClass = TypeMapper.RegistrationClassName(operation.OperationId);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {rootNamespace}.Endpoints;");
        sb.AppendLine();
        sb.AppendLine($"/// <summary>Optional registration customizer base for the <c>{operation.OperationId}</c> operation.</summary>");
        TypeMapper.AppendGeneratedAttributes(sb);
        sb.AppendLine($"public abstract class {registrationClass}");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Override to apply additional endpoint configuration such as authorization or rate limiting.</summary>");
        sb.AppendLine("    public virtual void Configure(global::Microsoft.AspNetCore.Builder.RouteHandlerBuilder builder) { }");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
