using System.Globalization;
using System.Text;

using MinimalOpenAPI.Abstractions.Models;

namespace MinimalOpenAPI.Client.Generator;

internal static class ClientCodeGenerator
{
    public static string Generate(OpenApiDocument document, string specName, string targetNamespace)
    {
        var registry = new TypeRegistry(document);
        var operations = document.Operations
            .OrderBy(static operation => operation.Route, StringComparer.Ordinal)
            .ThenBy(static operation => operation.HttpMethod, StringComparer.Ordinal)
            .Select(operation => CreateOperationModel(document, registry, operation))
            .ToArray();

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("using System.Globalization;");
        builder.AppendLine("using System.Net;");
        builder.AppendLine("using System.Net.Http.Json;");
        builder.AppendLine("using System.Text.Json;");
        builder.AppendLine("using System.Text.Json.Serialization;");
        builder.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        builder.AppendLine();
        builder.Append("namespace ").Append(targetNamespace).AppendLine(";");
        builder.AppendLine();

        for (var index = 0; index < registry.GeneratedTypes.Count; index++)
        {
            EmitType(builder, registry, registry.GeneratedTypes[index]);
            builder.AppendLine();
        }

        var clientName = ToPascalIdentifier(specName) + "Client";
        var exceptionName = clientName + "Exception";
        EmitException(builder, exceptionName);
        builder.AppendLine();
        EmitClient(builder, clientName, exceptionName, operations);
        builder.AppendLine();
        EmitRegistration(builder, clientName);

        return builder.ToString();
    }

    private static OperationModel CreateOperationModel(
        OpenApiDocument document,
        TypeRegistry registry,
        OpenApiOperation operation)
    {
        var operationName = string.IsNullOrWhiteSpace(operation.OperationId)
            ? ToPascalIdentifier(operation.HttpMethod + " " + operation.Route)
            : ToPascalIdentifier(operation.OperationId);

        var parameters = operation.Parameters
            .Select(parameter => ResolveParameter(document, parameter))
            .Select(parameter => new ParameterModel(
                parameter,
                ToCamelIdentifier(parameter.Name),
                registry.GetTypeName(
                    parameter.Schema,
                    operationName + ToPascalIdentifier(parameter.Name),
                    operationName + "Parameter" + ToPascalIdentifier(parameter.Name),
                    parameter.Required)))
            .ToArray();

        string? requestType = null;
        if (operation.RequestBody?.Schema is { } requestSchema)
        {
            requestType = registry.GetTypeName(
                requestSchema,
                operationName + "Request",
                operationName + "Request",
                operation.RequestBody.Required);
        }

        var successResponse = operation.Responses
            .Where(static response => response.StatusCode is >= 200 and <= 299)
            .OrderBy(static response => response.StatusCode)
            .FirstOrDefault();

        string? responseType = null;
        if (successResponse?.Schema is { } responseSchema)
        {
            responseType = registry.GetTypeName(
                responseSchema,
                operationName + "Response",
                operationName + "Response",
                required: true);
        }

        return new OperationModel(
            operationName,
            operation.HttpMethod,
            operation.Route,
            parameters,
            requestType,
            operation.RequestBody?.Required ?? false,
            operation.RequestBody?.ContentType,
            responseType);
    }

    private static OpenApiParameter ResolveParameter(OpenApiDocument document, OpenApiParameter parameter)
    {
        if (string.IsNullOrWhiteSpace(parameter.Reference))
            return parameter;

        const string prefix = "#/components/parameters/";
        if (!parameter.Reference.StartsWith(prefix, StringComparison.Ordinal))
            return parameter;

        var name = parameter.Reference.Substring(prefix.Length);
        return document.ComponentParameters.TryGetValue(name, out var resolved)
            ? resolved
            : parameter;
    }

    private static void EmitType(StringBuilder builder, TypeRegistry registry, GeneratedType type)
    {
        if (type.Schema.Enum is { Count: > 0 } enumValues)
        {
            builder.AppendLine("[JsonConverter(typeof(JsonStringEnumConverter))]");
            builder.Append("public enum ").Append(type.Name).AppendLine();
            builder.AppendLine("{");
            foreach (var value in enumValues)
            {
                var member = ToPascalIdentifier(value);
                builder.Append("    [JsonStringEnumMemberName(\"").Append(EscapeString(value)).AppendLine("\")]");
                builder.Append("    ").Append(member).AppendLine(",");
            }
            builder.AppendLine("}");
            return;
        }

        var properties = registry.GetEffectiveProperties(type.Schema);
        builder.Append("public sealed class ").Append(type.Name).AppendLine();
        builder.AppendLine("{");

        foreach (var property in properties.OrderBy(static property => property.Key, StringComparer.Ordinal))
        {
            var propertyName = ToPascalIdentifier(property.Key);
            var required = registry.IsRequired(type.Schema, property.Key);
            var propertyType = registry.GetTypeName(
                property.Value,
                type.Name + propertyName,
                type.Name + propertyName,
                required);

            builder.Append("    [JsonPropertyName(\"").Append(EscapeString(property.Key)).AppendLine("\")]");
            if (required && registry.IsReferenceType(propertyType) && !propertyType.EndsWith("?", StringComparison.Ordinal))
                builder.Append("    public required ");
            else
                builder.Append("    public ");

            builder.Append(propertyType).Append(' ').Append(propertyName).AppendLine(" { get; init; }");
            builder.AppendLine();
        }

        if (type.Schema.AdditionalPropertiesAllowed && properties.Count > 0)
        {
            builder.AppendLine("    [JsonExtensionData]");
            builder.AppendLine("    public Dictionary<string, JsonElement>? AdditionalProperties { get; init; }");
        }

        builder.AppendLine("}");
    }

    private static void EmitException(StringBuilder builder, string exceptionName)
    {
        builder.Append("public sealed class ").Append(exceptionName).AppendLine(" : HttpRequestException");
        builder.AppendLine("{");
        builder.Append("    public ").Append(exceptionName)
            .AppendLine("(HttpStatusCode statusCode, string? responseBody)")
            .AppendLine("        : base($\"The HTTP request failed with status code {(int)statusCode} ({statusCode}).\", null, statusCode)")
            .AppendLine("    {")
            .AppendLine("        StatusCode = statusCode;")
            .AppendLine("        ResponseBody = responseBody;")
            .AppendLine("    }")
            .AppendLine()
            .AppendLine("    public new HttpStatusCode StatusCode { get; }")
            .AppendLine("    public string? ResponseBody { get; }")
            .AppendLine("}");
    }

    private static void EmitClient(
        StringBuilder builder,
        string clientName,
        string exceptionName,
        IReadOnlyList<OperationModel> operations)
    {
        builder.Append("public sealed class ").Append(clientName).AppendLine("(HttpClient httpClient)");
        builder.AppendLine("{");
        builder.AppendLine("    private readonly HttpClient _httpClient = httpClient;");
        builder.AppendLine();

        foreach (var operation in operations)
        {
            EmitOperation(builder, exceptionName, operation);
            builder.AppendLine();
        }

        builder.AppendLine("    private static string FormatValue<T>(T value)");
        builder.AppendLine("        => value switch");
        builder.AppendLine("        {");
        builder.AppendLine("            null => string.Empty,");
        builder.AppendLine("            bool boolean => boolean ? \"true\" : \"false\",");
        builder.AppendLine("            IFormattable formattable => formattable.ToString(null, CultureInfo.InvariantCulture),");
        builder.AppendLine("            _ => value.ToString() ?? string.Empty");
        builder.AppendLine("        };");
        builder.AppendLine();
        builder.AppendLine("    private static string Encode<T>(T value) => Uri.EscapeDataString(FormatValue(value));");
        builder.AppendLine("}");
    }

    private static void EmitOperation(StringBuilder builder, string exceptionName, OperationModel operation)
    {
        var returnType = operation.ResponseType is null ? "Task" : $"Task<{operation.ResponseType}>";
        builder.Append("    public async ").Append(returnType).Append(' ').Append(operation.Name).Append("Async(");

        var methodParameters = new List<string>();
        foreach (var parameter in operation.Parameters)
            methodParameters.Add($"{parameter.TypeName} {parameter.VariableName}");

        if (operation.RequestType is not null)
        {
            var bodyType = operation.RequestRequired || operation.RequestType.EndsWith("?", StringComparison.Ordinal)
                ? operation.RequestType
                : operation.RequestType + "?";
            methodParameters.Add($"{bodyType} body");
        }

        methodParameters.Add("CancellationToken cancellationToken = default");
        builder.Append(string.Join(", ", methodParameters)).AppendLine(")");
        builder.AppendLine("    {");
        builder.Append("        var path = \"").Append(EscapeString(operation.Route)).AppendLine("\";");

        foreach (var parameter in operation.Parameters.Where(static parameter => parameter.Parameter.Location == ParameterLocation.Path))
        {
            builder.Append("        path = path.Replace(\"{").Append(EscapeString(parameter.Parameter.Name)).Append("}\", Encode(")
                .Append(parameter.VariableName).AppendLine("), StringComparison.Ordinal);");
        }

        var queryParameters = operation.Parameters.Where(static parameter => parameter.Parameter.Location == ParameterLocation.Query).ToArray();
        if (queryParameters.Length > 0)
        {
            builder.AppendLine("        var query = new List<string>();");
            foreach (var parameter in queryParameters)
                EmitQueryParameter(builder, parameter);
            builder.AppendLine("        if (query.Count > 0)");
            builder.AppendLine("            path += \"?\" + string.Join(\"&\", query);");
        }

        builder.Append("        using var request = new HttpRequestMessage(new HttpMethod(\"")
            .Append(EscapeString(operation.HttpMethod.ToUpperInvariant()))
            .AppendLine("\"), path);");

        foreach (var parameter in operation.Parameters.Where(static parameter => parameter.Parameter.Location == ParameterLocation.Header))
            EmitHeaderParameter(builder, parameter);

        var cookieParameters = operation.Parameters.Where(static parameter => parameter.Parameter.Location == ParameterLocation.Cookie).ToArray();
        if (cookieParameters.Length > 0)
        {
            builder.AppendLine("        var cookies = new List<string>();");
            foreach (var parameter in cookieParameters)
                EmitCookieParameter(builder, parameter);
            builder.AppendLine("        if (cookies.Count > 0)");
            builder.AppendLine("            request.Headers.TryAddWithoutValidation(\"Cookie\", string.Join(\"; \", cookies));");
        }

        if (operation.RequestType is not null)
        {
            if (operation.RequestContentType is null || operation.RequestContentType.IndexOf("json", StringComparison.OrdinalIgnoreCase) >= 0)
            {
                builder.AppendLine("        request.Content = JsonContent.Create(body);");
            }
            else
            {
                builder.AppendLine("        request.Content = JsonContent.Create(body);");
                builder.Append("        request.Content.Headers.ContentType = new System.Net.Http.Headers.MediaTypeHeaderValue(\"")
                    .Append(EscapeString(operation.RequestContentType)).AppendLine("\");");
            }
        }

        builder.AppendLine("        using var response = await _httpClient.SendAsync(request, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);");
        builder.AppendLine("        if (!response.IsSuccessStatusCode)");
        builder.AppendLine("        {");
        builder.AppendLine("            var responseBody = response.Content is null");
        builder.AppendLine("                ? null");
        builder.AppendLine("                : await response.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);");
        builder.Append("            throw new ").Append(exceptionName).AppendLine("(response.StatusCode, responseBody);");
        builder.AppendLine("        }");

        if (operation.ResponseType is not null)
        {
            builder.Append("        return await response.Content.ReadFromJsonAsync<").Append(operation.ResponseType)
                .AppendLine(">(cancellationToken: cancellationToken).ConfigureAwait(false)")
                .AppendLine("            ?? throw new JsonException(\"The response body was empty.\");");
        }

        builder.AppendLine("    }");
    }

    private static void EmitQueryParameter(StringBuilder builder, ParameterModel parameter)
    {
        var name = EscapeString(parameter.Parameter.Name);
        var variable = parameter.VariableName;
        if (parameter.Parameter.Schema.Type == "array")
        {
            if (!parameter.Parameter.Required)
                builder.Append("        if (").Append(variable).AppendLine(" is not null)");
            builder.AppendLine("        {");
            builder.Append("            foreach (var item in ").Append(variable).AppendLine(")");
            builder.Append("                query.Add(\"").Append(name).Append("=\" + Encode(item));").AppendLine();
            builder.AppendLine("        }");
            return;
        }

        if (!parameter.Parameter.Required || parameter.Parameter.Schema.Nullable)
        {
            builder.Append("        if (").Append(variable).AppendLine(" is not null)");
            builder.Append("            query.Add(\"").Append(name).Append("=\" + Encode(").Append(variable).AppendLine("));");
        }
        else
        {
            builder.Append("        query.Add(\"").Append(name).Append("=\" + Encode(").Append(variable).AppendLine("));");
        }
    }

    private static void EmitHeaderParameter(StringBuilder builder, ParameterModel parameter)
    {
        var name = EscapeString(parameter.Parameter.Name);
        if (!parameter.Parameter.Required || parameter.Parameter.Schema.Nullable)
        {
            builder.Append("        if (").Append(parameter.VariableName).AppendLine(" is not null)");
            builder.Append("            request.Headers.TryAddWithoutValidation(\"").Append(name).Append("\", FormatValue(")
                .Append(parameter.VariableName).AppendLine("));");
        }
        else
        {
            builder.Append("        request.Headers.TryAddWithoutValidation(\"").Append(name).Append("\", FormatValue(")
                .Append(parameter.VariableName).AppendLine("));");
        }
    }

    private static void EmitCookieParameter(StringBuilder builder, ParameterModel parameter)
    {
        var name = EscapeString(parameter.Parameter.Name);
        if (!parameter.Parameter.Required || parameter.Parameter.Schema.Nullable)
        {
            builder.Append("        if (").Append(parameter.VariableName).AppendLine(" is not null)");
            builder.Append("            cookies.Add(\"").Append(name).Append("=\" + Encode(").Append(parameter.VariableName).AppendLine("));");
        }
        else
        {
            builder.Append("        cookies.Add(\"").Append(name).Append("=\" + Encode(").Append(parameter.VariableName).AppendLine("));");
        }
    }

    private static void EmitRegistration(StringBuilder builder, string clientName)
    {
        builder.Append("public static class ").Append(clientName).AppendLine("ServiceCollectionExtensions");
        builder.AppendLine("{");
        builder.Append("    public static IServiceCollection Add").Append(clientName)
            .AppendLine("(this IServiceCollection services, Action<HttpClient> configureClient)")
            .AppendLine("    {")
            .Append("        services.AddHttpClient<").Append(clientName).AppendLine(">(configureClient);")
            .AppendLine("        return services;")
            .AppendLine("    }")
            .AppendLine()
            .Append("    public static IServiceCollection Add").Append(clientName)
            .AppendLine("(this IServiceCollection services, Uri baseAddress)")
            .AppendLine("        => services.Add" + clientName + "(client => client.BaseAddress = baseAddress);")
            .AppendLine("}");
    }

    internal static string ToPascalIdentifier(string value)
    {
        if (string.IsNullOrWhiteSpace(value))
            return "Api";

        var builder = new StringBuilder();
        var capitalize = true;
        foreach (var character in value)
        {
            if (!char.IsLetterOrDigit(character))
            {
                capitalize = true;
                continue;
            }

            builder.Append(capitalize ? char.ToUpperInvariant(character) : character);
            capitalize = false;
        }

        if (builder.Length == 0)
            return "Api";
        if (char.IsDigit(builder[0]))
            builder.Insert(0, '_');
        return builder.ToString();
    }

    private static string ToCamelIdentifier(string value)
    {
        var pascal = ToPascalIdentifier(value);
        return pascal.Length == 1
            ? pascal.ToLowerInvariant()
            : char.ToLowerInvariant(pascal[0]) + pascal.Substring(1);
    }

    private static string EscapeString(string value)
        => value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private sealed record OperationModel(
        string Name,
        string HttpMethod,
        string Route,
        IReadOnlyList<ParameterModel> Parameters,
        string? RequestType,
        bool RequestRequired,
        string? RequestContentType,
        string? ResponseType);

    private sealed record ParameterModel(OpenApiParameter Parameter, string VariableName, string TypeName);

    private sealed class TypeRegistry
    {
        private readonly OpenApiDocument _document;
        private readonly Dictionary<string, GeneratedType> _typesByName = new(StringComparer.Ordinal);

        public TypeRegistry(OpenApiDocument document)
        {
            _document = document;
            foreach (var schema in document.Schemas.OrderBy(static pair => pair.Key, StringComparer.Ordinal))
            {
                if (NeedsGeneratedType(schema.Value))
                    Register(ToPascalIdentifier(schema.Key), ToPascalIdentifier(schema.Key), schema.Value);
            }
        }

        public List<GeneratedType> GeneratedTypes { get; } = new();

        public string GetTypeName(OpenApiSchema schema, string preferredName, string qualifiedName, bool required)
        {
            var typeName = GetNonNullableTypeName(schema, preferredName, qualifiedName);
            if (required && !schema.Nullable)
                return typeName;

            return typeName.EndsWith("?", StringComparison.Ordinal) ? typeName : typeName + "?";
        }

        public bool IsReferenceType(string typeName)
        {
            var value = typeName.TrimEnd('?');
            return value is "string" or "object" ||
                   value.StartsWith("IReadOnlyList<", StringComparison.Ordinal) ||
                   value.StartsWith("Dictionary<", StringComparison.Ordinal) ||
                   _typesByName.TryGetValue(value, out var generated) && generated.Schema.Enum is null;
        }

        public IReadOnlyDictionary<string, OpenApiSchema> GetEffectiveProperties(OpenApiSchema schema)
        {
            var result = new Dictionary<string, OpenApiSchema>(StringComparer.Ordinal);
            AddProperties(schema, result, new HashSet<string>(StringComparer.Ordinal));
            return result;
        }

        public bool IsRequired(OpenApiSchema schema, string propertyName)
        {
            var required = new HashSet<string>(StringComparer.Ordinal);
            AddRequired(schema, required, new HashSet<string>(StringComparer.Ordinal));
            return required.Contains(propertyName);
        }

        private string GetNonNullableTypeName(OpenApiSchema schema, string preferredName, string qualifiedName)
        {
            if (!string.IsNullOrWhiteSpace(schema.Reference))
            {
                if (_document.Schemas.TryGetValue(schema.Reference, out var referenced))
                {
                    if (NeedsGeneratedType(referenced))
                        return Register(ToPascalIdentifier(schema.Reference), ToPascalIdentifier(schema.Reference), referenced);
                    return GetNonNullableTypeName(referenced, preferredName, qualifiedName);
                }

                return ToPascalIdentifier(schema.Reference);
            }

            if (schema.Enum is { Count: > 0 })
                return Register(preferredName, qualifiedName, schema);

            if (schema.Type == "array")
            {
                var itemType = schema.Items is null
                    ? "object"
                    : GetTypeName(schema.Items, preferredName + "Item", qualifiedName + "Item", required: true);
                return $"IReadOnlyList<{itemType}>";
            }

            if ((schema.Type == "object" || schema.Type is null) &&
                schema.Properties.Count == 0 &&
                schema.AllOf.Count == 0 &&
                (schema.AdditionalProperties is not null || schema.AdditionalPropertiesAllowed))
            {
                var valueType = schema.AdditionalProperties is null
                    ? "object"
                    : GetTypeName(schema.AdditionalProperties, preferredName + "Value", qualifiedName + "Value", required: true);
                return $"Dictionary<string, {valueType}>";
            }

            if (NeedsGeneratedType(schema))
                return Register(preferredName, qualifiedName, schema);

            return schema.Type switch
            {
                "string" when schema.Format == "uuid" => "Guid",
                "string" when schema.Format == "date-time" => "DateTimeOffset",
                "string" when schema.Format == "date" => "DateOnly",
                "string" => "string",
                "integer" when schema.Format == "int64" => "long",
                "integer" => "int",
                "number" when schema.Format == "float" => "float",
                "number" => "double",
                "boolean" => "bool",
                "object" => "object",
                _ => "object"
            };
        }

        private string Register(string preferredName, string qualifiedName, OpenApiSchema schema)
        {
            var preferred = ToPascalIdentifier(preferredName);
            if (!_typesByName.TryGetValue(preferred, out var existing))
                return Add(preferred, schema);
            if (Fingerprint(existing.Schema) == Fingerprint(schema))
                return preferred;

            var qualified = ToPascalIdentifier(qualifiedName);
            if (!_typesByName.TryGetValue(qualified, out existing))
                return Add(qualified, schema);
            if (Fingerprint(existing.Schema) == Fingerprint(schema))
                return qualified;

            for (var suffix = 2; ; suffix++)
            {
                var candidate = qualified + suffix.ToString(CultureInfo.InvariantCulture);
                if (!_typesByName.ContainsKey(candidate))
                    return Add(candidate, schema);
            }
        }

        private string Add(string name, OpenApiSchema schema)
        {
            var generated = new GeneratedType(name, schema);
            _typesByName.Add(name, generated);
            GeneratedTypes.Add(generated);
            return name;
        }

        private static bool NeedsGeneratedType(OpenApiSchema schema)
            => schema.Enum is { Count: > 0 } ||
               schema.Properties.Count > 0 ||
               schema.AllOf.Count > 0;

        private void AddProperties(
            OpenApiSchema schema,
            Dictionary<string, OpenApiSchema> target,
            HashSet<string> visitedReferences)
        {
            if (!string.IsNullOrWhiteSpace(schema.Reference) &&
                visitedReferences.Add(schema.Reference) &&
                _document.Schemas.TryGetValue(schema.Reference, out var referenced))
            {
                AddProperties(referenced, target, visitedReferences);
            }

            foreach (var part in schema.AllOf)
                AddProperties(part, target, visitedReferences);

            foreach (var property in schema.Properties)
                target[property.Key] = property.Value;
        }

        private void AddRequired(OpenApiSchema schema, HashSet<string> target, HashSet<string> visitedReferences)
        {
            if (!string.IsNullOrWhiteSpace(schema.Reference) &&
                visitedReferences.Add(schema.Reference) &&
                _document.Schemas.TryGetValue(schema.Reference, out var referenced))
            {
                AddRequired(referenced, target, visitedReferences);
            }

            foreach (var part in schema.AllOf)
                AddRequired(part, target, visitedReferences);

            foreach (var required in schema.Required)
                target.Add(required);
        }

        private static string Fingerprint(OpenApiSchema schema)
        {
            var builder = new StringBuilder();
            AppendFingerprint(builder, schema);
            return builder.ToString();
        }

        private static void AppendFingerprint(StringBuilder builder, OpenApiSchema schema)
        {
            builder.Append(schema.Reference).Append('|')
                .Append(schema.Type).Append('|')
                .Append(schema.Format).Append('|')
                .Append(schema.Nullable).Append('|');

            if (schema.Enum is { } values)
            {
                foreach (var value in values)
                    builder.Append("e:").Append(value).Append(';');
            }

            foreach (var property in schema.Properties.OrderBy(static pair => pair.Key, StringComparer.Ordinal))
            {
                builder.Append("p:").Append(property.Key).Append('{');
                AppendFingerprint(builder, property.Value);
                builder.Append('}');
            }

            foreach (var part in schema.AllOf)
            {
                builder.Append("a{");
                AppendFingerprint(builder, part);
                builder.Append('}');
            }

            if (schema.Items is not null)
            {
                builder.Append("i{");
                AppendFingerprint(builder, schema.Items);
                builder.Append('}');
            }
        }
    }

    private sealed record GeneratedType(string Name, OpenApiSchema Schema);
}
