using System.Globalization;
using System.Text;

using MinimalOpenAPI.Abstractions.Models;

namespace MinimalOpenAPIClient.Generator;

internal static class ClientCodeGenerator
{
    public static string Generate(OpenApiDocument document, string specName, string targetNamespace)
    {
        var clientName = ToPascalIdentifier(specName) + "Client";
        var exceptionName = clientName + "Exception";
        var extensionName = clientName + "ServiceCollectionExtensions";

        var registry = new TypeRegistry(document, [clientName, exceptionName, extensionName]);
        var operationNames = new NameAllocator();
        var operations = document.Operations
            .OrderBy(static operation => operation.Route, StringComparer.Ordinal)
            .ThenBy(static operation => operation.HttpMethod, StringComparer.Ordinal)
            .Select(operation =>
            {
                var preferredName = string.IsNullOrWhiteSpace(operation.OperationId)
                    ? ToPascalIdentifier(operation.HttpMethod + " " + operation.Route)
                    : ToPascalIdentifier(operation.OperationId);
                return CreateOperationModel(document, registry, operation, operationNames.Allocate(preferredName));
            })
            .ToArray();

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("using System;");
        builder.AppendLine("using System.Collections.Generic;");
        builder.AppendLine("using System.Globalization;");
        builder.AppendLine("using System.Net;");
        builder.AppendLine("using System.Net.Http;");
        builder.AppendLine("using System.Net.Http.Json;");
        builder.AppendLine("using System.Text.Json;");
        builder.AppendLine("using System.Text.Json.Serialization;");
        builder.AppendLine("using System.Threading;");
        builder.AppendLine("using System.Threading.Tasks;");
        builder.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        builder.AppendLine();
        builder.Append("namespace ").Append(targetNamespace).AppendLine(";");
        builder.AppendLine();

        for (var index = 0; index < registry.GeneratedTypes.Count; index++)
        {
            EmitType(builder, registry, registry.GeneratedTypes[index]);
            builder.AppendLine();
        }

        EmitException(builder, exceptionName);
        builder.AppendLine();
        EmitClient(builder, clientName, exceptionName, operations);
        builder.AppendLine();
        EmitRegistration(builder, clientName);

        return builder.ToString();
    }

    private static OperationModel CreateOperationModel(
        OpenApiDocument document,
        TypeRegistry registry,
        OpenApiOperation operation,
        string operationName)
    {
        var variableNames = new NameAllocator(["body", "cancellationToken", "path", "query", "request", "response", "responseBody", "cookies", "item", "_httpClient"]);
        var parameters = MergeParameters(document, operation.Parameters)
            .Select(parameter => new ParameterModel(
                parameter,
                "@" + variableNames.Allocate(ToCamelIdentifier(parameter.Name)),
                registry.GetTypeName(
                    parameter.Schema,
                    operationName + ToPascalIdentifier(parameter.Name),
                    operationName + "Parameter" + ToPascalIdentifier(parameter.Name),
                    parameter.Required)))
            .ToArray();

        string? requestType = null;
        var requestBody = operation.RequestBody;
        if (requestBody is not null && requestBody.Schema is null)
            throw new ClientGenerationException($"Operation '{operationName}' has an unsupported request body. Only JSON request bodies with a schema are supported.");

        foreach (var parameter in parameters)
        {
            var schema = registry.ResolveSchema(parameter.Parameter.Schema);
            var location = parameter.Parameter.Location;
            var defaultStyle = location is ParameterLocation.Query or ParameterLocation.Cookie ? "form" : "simple";
            if (parameter.Parameter.Style is { } style && style != defaultStyle ||
                parameter.Parameter.AllowReserved ||
                schema.Type == "array" && (location != ParameterLocation.Query || parameter.Parameter.Explode == false) ||
                schema.Type is null or "object" || schema.Properties.Count > 0 || schema.AllOf.Count > 0)
            {
                throw new ClientGenerationException($"Parameter '{parameter.Parameter.Name}' in operation '{operationName}' uses unsupported serialization. Only scalar parameters and exploded form-style query arrays are supported.");
            }
        }
        if (requestBody?.Schema is { } requestSchema)
        {
            var contentType = requestBody.ContentType;
            if (!string.IsNullOrWhiteSpace(contentType) &&
                contentType!.IndexOf("json", StringComparison.OrdinalIgnoreCase) < 0)
            {
                throw new ClientGenerationException(
                    $"Operation '{operationName}' uses unsupported request content type '{contentType}'. Only JSON request bodies are currently supported.");
            }

            requestType = registry.GetTypeName(
                requestSchema,
                operationName + "Request",
                operationName + "Request",
                requestBody.Required,
                SchemaScope.Request);
        }

        var successResponse = operation.Responses
            .Where(static response => response.StatusCode is >= 200 and <= 299)
            .OrderBy(static response => response.StatusCode)
            .FirstOrDefault();

        string? responseType = null;
        if (successResponse?.Schema is { } responseSchema)
        {
            responseType = registry.GetTypeName(
                responseSchema,
                operationName + "Response",
                operationName + "Response",
                required: true,
                SchemaScope.Response);
        }

        foreach (var response in operation.Responses.Where(static response => response.StatusCode is >= 200 and <= 299))
        {
            if (response.Reference is not null || response.HasContentRepresentations && response.Schema is null)
                throw new ClientGenerationException($"Operation '{operationName}' has an unsupported success response. Only inline response definitions with JSON schemas or no content are supported.");
            var candidateType = response.Schema is null ? null : registry.GetTypeName(
                response.Schema, operationName + "Response", operationName + "Response", required: true, SchemaScope.Response);
            if (candidateType != responseType)
                throw new ClientGenerationException($"Operation '{operationName}' has incompatible success response schemas. All success responses must have the same body shape.");
        }

        return new OperationModel(
            operationName,
            operation.HttpMethod,
            operation.Route,
            parameters,
            requestType,
            requestBody?.Required ?? false,
            requestBody?.ContentType,
            responseType);
    }

    private static IReadOnlyList<OpenApiParameter> MergeParameters(
        OpenApiDocument document,
        IReadOnlyList<OpenApiParameter> parameters)
    {
        var merged = new List<OpenApiParameter>();
        var indexes = new Dictionary<(string Name, ParameterLocation Location), int>();

        foreach (var rawParameter in parameters)
        {
            var parameter = ResolveParameter(document, rawParameter);
            var key = (parameter.Name, parameter.Location);
            if (indexes.TryGetValue(key, out var index))
            {
                merged[index] = parameter;
            }
            else
            {
                indexes.Add(key, merged.Count);
                merged.Add(parameter);
            }
        }

        return merged;
    }

    private static OpenApiParameter ResolveParameter(OpenApiDocument document, OpenApiParameter parameter)
    {
        var reference = parameter.Reference ?? string.Empty;
        if (string.IsNullOrWhiteSpace(reference))
            return parameter;

        const string prefix = "#/components/parameters/";
        if (!reference.StartsWith(prefix, StringComparison.Ordinal))
            throw new ClientGenerationException($"External or unsupported parameter reference '{reference}' is not supported.");

        var name = reference.Substring(prefix.Length).Replace("~1", "/").Replace("~0", "~");
        if (!document.ComponentParameters.TryGetValue(name, out var resolved))
            throw new ClientGenerationException($"Unable to resolve parameter reference '{reference}'.");

        return resolved;
    }

    private static void EmitType(StringBuilder builder, TypeRegistry registry, GeneratedType type)
    {
        if (type.Schema.Enum is { Count: > 0 } enumValues)
        {
            var memberNames = new NameAllocator([type.Name]);
            builder.AppendLine("[JsonConverter(typeof(JsonStringEnumConverter))]");
            builder.Append("public enum ").Append(type.Name).AppendLine();
            builder.AppendLine("{");
            foreach (var value in enumValues)
            {
                var member = memberNames.Allocate(ToPascalIdentifier(value));
                builder.Append("    [JsonStringEnumMemberName(\"").Append(EscapeString(value)).AppendLine("\")]");
                builder.Append("    ").Append(member).AppendLine(",");
            }
            builder.AppendLine("}");
            return;
        }

        var propertyNames = new NameAllocator([type.Name, "AdditionalProperties"]);
        var properties = registry.GetEffectiveProperties(type.Schema);
        builder.Append("public sealed class ").Append(type.Name).AppendLine();
        builder.AppendLine("{");

        foreach (var property in properties.OrderBy(static property => property.Key, StringComparer.Ordinal))
        {
            if (type.Scope == SchemaScope.Request && property.Value.ReadOnly ||
                type.Scope == SchemaScope.Response && property.Value.WriteOnly)
                continue;

            var propertyName = propertyNames.Allocate(ToPascalIdentifier(property.Key));
            var required = registry.IsRequired(type.Schema, property.Key);
            var propertyType = registry.GetTypeName(
                property.Value,
                type.Name + propertyName,
                type.Name + propertyName,
                required,
                type.Scope);

            builder.Append("    [JsonPropertyName(\"").Append(EscapeString(property.Key)).AppendLine("\")]");
            if (!required)
                builder.AppendLine("    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]");
            if (required)
                builder.Append("    public required ");
            else
                builder.Append("    public ");

            builder.Append(propertyType).Append(' ').Append(propertyName).AppendLine(" { get; init; }");
            builder.AppendLine();
        }

        if (type.Schema.AdditionalPropertiesAllowed && properties.Count > 0)
        {
            builder.AppendLine("    [JsonExtensionData]");
            builder.AppendLine("    public Dictionary<string, JsonElement>? AdditionalProperties { get; init; }");
        }

        builder.AppendLine("}");
    }

    private static void EmitException(StringBuilder builder, string exceptionName)
    {
        builder.Append("public sealed class ").Append(exceptionName).AppendLine(" : HttpRequestException");
        builder.AppendLine("{");
        builder.Append("    public ").Append(exceptionName)
            .AppendLine("(HttpStatusCode statusCode, string? responseBody)")
            .AppendLine("        : base($\"The HTTP request failed with status code {(int)statusCode} ({statusCode}).\", null, statusCode)")
            .AppendLine("    {")
            .AppendLine("        StatusCode = statusCode;")
            .AppendLine("        ResponseBody = responseBody;")
            .AppendLine("    }")
            .AppendLine()
            .AppendLine("    public new HttpStatusCode StatusCode { get; }")
            .AppendLine("    public string? ResponseBody { get; }")
            .AppendLine("}");
    }

    private static void EmitClient(
        StringBuilder builder,
        string clientName,
        string exceptionName,
        IReadOnlyList<OperationModel> operations)
    {
        builder.Append("public sealed class ").Append(clientName).AppendLine();
        builder.AppendLine("{");
        builder.AppendLine("    private readonly HttpClient _httpClient;");
        builder.AppendLine();
        builder.Append("    public ").Append(clientName).AppendLine("(HttpClient httpClient)");
        builder.AppendLine("    {");
        builder.AppendLine("        _httpClient = httpClient;");
        builder.AppendLine("    }");
        builder.AppendLine();

        foreach (var operation in operations)
        {
            EmitOperation(builder, exceptionName, operation);
            builder.AppendLine();
        }

        builder.AppendLine("    private static string FormatValue<T>(T value)");
        builder.AppendLine("        => value switch");
        builder.AppendLine("        {");
        builder.AppendLine("            null => string.Empty,");
        builder.AppendLine("            bool boolean => boolean ? \"true\" : \"false\",");
        builder.AppendLine("            DateOnly date => date.ToString(\"yyyy-MM-dd\", CultureInfo.InvariantCulture),");
        builder.AppendLine("            DateTimeOffset timestamp => timestamp.ToString(\"O\", CultureInfo.InvariantCulture),");
        builder.AppendLine("            Enum enumValue => JsonSerializer.Deserialize<string>(JsonSerializer.Serialize(enumValue, enumValue.GetType())) ?? string.Empty,");
        builder.AppendLine("            IFormattable formattable => formattable.ToString(null, CultureInfo.InvariantCulture),");
        builder.AppendLine("            _ => value.ToString() ?? string.Empty");
        builder.AppendLine("        };");
        builder.AppendLine();
        builder.AppendLine("    private static string Encode<T>(T value) => Uri.EscapeDataString(FormatValue(value));");
        builder.AppendLine();
        builder.AppendLine("    private Uri CreateRequestUri(string path)");
        builder.AppendLine("    {");
        builder.AppendLine("        if (_httpClient.BaseAddress is not { } baseAddress)");
        builder.AppendLine("            return new Uri(path, UriKind.Relative);");
        builder.AppendLine("        var builder = new UriBuilder(baseAddress);");
        builder.AppendLine("        if (!builder.Path.EndsWith(\"/\", StringComparison.Ordinal))");
        builder.AppendLine("            builder.Path += \"/\";");
        builder.AppendLine("        return new Uri(builder.Uri, path);");
        builder.AppendLine("    }");
        builder.AppendLine("}");
    }

    private static void EmitOperation(StringBuilder builder, string exceptionName, OperationModel operation)
    {
        var returnType = operation.ResponseType is null ? "Task" : $"Task<{operation.ResponseType}>";
        builder.Append("    public async ").Append(returnType).Append(' ').Append(operation.Name).Append("Async(");

        var methodParameters = new List<string>();
        foreach (var parameter in operation.Parameters.Where(static parameter => parameter.Parameter.Required))
            methodParameters.Add($"{parameter.TypeName} {parameter.VariableName}");

        if (operation.RequestType is not null && operation.RequestRequired)
            methodParameters.Add($"{operation.RequestType} body");

        foreach (var parameter in operation.Parameters.Where(static parameter => !parameter.Parameter.Required))
            methodParameters.Add($"{parameter.TypeName} {parameter.VariableName} = null");

        if (operation.RequestType is not null && !operation.RequestRequired)
        {
            var bodyType = operation.RequestRequired || operation.RequestType.EndsWith("?", StringComparison.Ordinal)
                ? operation.RequestType
                : operation.RequestType + "?";
            methodParameters.Add(operation.RequestRequired
                ? $"{bodyType} body"
                : $"{bodyType} body = null");
        }

        methodParameters.Add("CancellationToken cancellationToken = default");
        builder.Append(string.Join(", ", methodParameters)).AppendLine(")");
        builder.AppendLine("    {");
        builder.Append("        var path = \"").Append(EscapeString(operation.Route.TrimStart('/'))).AppendLine("\";");

        foreach (var parameter in operation.Parameters.Where(static parameter => parameter.Parameter.Location == ParameterLocation.Path))
        {
            builder.Append("        path = path.Replace(\"{").Append(EscapeString(parameter.Parameter.Name)).Append("}\", Encode(")
                .Append(parameter.VariableName).AppendLine("), StringComparison.Ordinal);");
        }

        var queryParameters = operation.Parameters.Where(static parameter => parameter.Parameter.Location == ParameterLocation.Query).ToArray();
        if (queryParameters.Length > 0)
        {
            builder.AppendLine("        var query = new List<string>();");
            foreach (var parameter in queryParameters)
                EmitQueryParameter(builder, parameter);
            builder.AppendLine("        if (query.Count > 0)");
            builder.AppendLine("            path += \"?\" + string.Join(\"&\", query);");
        }

        builder.Append("        using var request = new HttpRequestMessage(new HttpMethod(\"")
            .Append(EscapeString(operation.HttpMethod.ToUpperInvariant()))
            .AppendLine("\"), CreateRequestUri(path));");

        foreach (var parameter in operation.Parameters.Where(static parameter => parameter.Parameter.Location == ParameterLocation.Header))
            EmitHeaderParameter(builder, parameter);

        var cookieParameters = operation.Parameters.Where(static parameter => parameter.Parameter.Location == ParameterLocation.Cookie).ToArray();
        if (cookieParameters.Length > 0)
        {
            builder.AppendLine("        var cookies = new List<string>();");
            foreach (var parameter in cookieParameters)
                EmitCookieParameter(builder, parameter);
            builder.AppendLine("        if (cookies.Count > 0)");
            builder.AppendLine("            request.Headers.TryAddWithoutValidation(\"Cookie\", string.Join(\"; \", cookies));");
        }

        if (operation.RequestType is not null)
        {
            var indent = "        ";
            if (!operation.RequestRequired)
            {
                builder.AppendLine("        if (body is not null)");
                builder.AppendLine("        {");
                indent = "            ";
            }

            builder.Append(indent).AppendLine("request.Content = JsonContent.Create(body);");

            if (!operation.RequestRequired)
                builder.AppendLine("        }");
        }

        builder.AppendLine("        using var response = await _httpClient.SendAsync(request, HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);");
        builder.AppendLine("        if (!response.IsSuccessStatusCode)");
        builder.AppendLine("        {");
        builder.AppendLine("            var responseBody = response.Content is null");
        builder.AppendLine("                ? null");
        builder.AppendLine("                : await response.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);");
        builder.Append("            throw new ").Append(exceptionName).AppendLine("(response.StatusCode, responseBody);");
        builder.AppendLine("        }");

        if (operation.ResponseType is not null)
        {
            builder.AppendLine("        if (response.Content is null)");
            builder.AppendLine("            throw new JsonException(\"The response body was empty.\");");
            var nullable = operation.ResponseType.EndsWith("?", StringComparison.Ordinal);
            builder.Append("        return await response.Content.ReadFromJsonAsync<").Append(operation.ResponseType)
                .Append(nullable ? string.Empty : "?")
                .Append(">(cancellationToken: cancellationToken).ConfigureAwait(false)");
            if (!nullable)
                builder.AppendLine().Append("            ?? throw new JsonException(\"The response body was null.\")");
            builder.AppendLine(";");
        }

        builder.AppendLine("    }");
    }

    private static void EmitQueryParameter(StringBuilder builder, ParameterModel parameter)
    {
        var name = EscapeString(Uri.EscapeDataString(parameter.Parameter.Name));
        var variable = parameter.VariableName;
        if (parameter.TypeName.StartsWith("IReadOnlyList<", StringComparison.Ordinal))
        {
            if (parameter.TypeName.EndsWith("?", StringComparison.Ordinal))
                builder.Append("        if (").Append(variable).AppendLine(" is not null)");
            builder.AppendLine("        {");
            builder.Append("            foreach (var item in ").Append(variable).AppendLine(")");
            builder.Append("                query.Add(\"").Append(name).Append("=\" + Encode(item));").AppendLine();
            builder.AppendLine("        }");
            return;
        }

        if (parameter.TypeName.EndsWith("?", StringComparison.Ordinal))
        {
            builder.Append("        if (").Append(variable).AppendLine(" is not null)");
            builder.Append("            query.Add(\"").Append(name).Append("=\" + Encode(").Append(variable).AppendLine("));");
        }
        else
        {
            builder.Append("        query.Add(\"").Append(name).Append("=\" + Encode(").Append(variable).AppendLine("));");
        }
    }

    private static void EmitHeaderParameter(StringBuilder builder, ParameterModel parameter)
    {
        var name = EscapeString(parameter.Parameter.Name);
        if (parameter.TypeName.EndsWith("?", StringComparison.Ordinal))
        {
            builder.Append("        if (").Append(parameter.VariableName).AppendLine(" is not null)");
            builder.Append("            request.Headers.TryAddWithoutValidation(\"").Append(name).Append("\", FormatValue(")
                .Append(parameter.VariableName).AppendLine("));");
        }
        else
        {
            builder.Append("        request.Headers.TryAddWithoutValidation(\"").Append(name).Append("\", FormatValue(")
                .Append(parameter.VariableName).AppendLine("));");
        }
    }

    private static void EmitCookieParameter(StringBuilder builder, ParameterModel parameter)
    {
        var name = EscapeString(parameter.Parameter.Name);
        if (parameter.TypeName.EndsWith("?", StringComparison.Ordinal))
        {
            builder.Append("        if (").Append(parameter.VariableName).AppendLine(" is not null)");
            builder.Append("            cookies.Add(\"").Append(name).Append("=\" + Encode(").Append(parameter.VariableName).AppendLine("));");
        }
        else
        {
            builder.Append("        cookies.Add(\"").Append(name).Append("=\" + Encode(").Append(parameter.VariableName).AppendLine("));");
        }
    }

    private static void EmitRegistration(StringBuilder builder, string clientName)
    {
        builder.Append("public static class ").Append(clientName).AppendLine("ServiceCollectionExtensions");
        builder.AppendLine("{");
        builder.Append("    public static IServiceCollection Add").Append(clientName)
            .AppendLine("(this IServiceCollection services, Action<HttpClient> configureClient)")
            .AppendLine("    {")
            .Append("        services.AddHttpClient<").Append(clientName).AppendLine(">(configureClient);")
            .AppendLine("        return services;")
            .AppendLine("    }")
            .AppendLine()
            .Append("    public static IServiceCollection Add").Append(clientName)
            .AppendLine("(this IServiceCollection services, Uri baseAddress)")
            .AppendLine("        => services.Add" + clientName + "(client => client.BaseAddress = baseAddress);")
            .AppendLine("}");
    }

    internal static string ToPascalIdentifier(string value)
    {
        if (string.IsNullOrWhiteSpace(value))
            return "Api";

        var builder = new StringBuilder();
        var capitalize = true;
        foreach (var character in value)
        {
            if (!char.IsLetterOrDigit(character))
            {
                capitalize = true;
                continue;
            }

            builder.Append(capitalize ? char.ToUpperInvariant(character) : character);
            capitalize = false;
        }

        if (builder.Length == 0)
            return "Api";
        if (char.IsDigit(builder[0]))
            builder.Insert(0, '_');
        return builder.ToString();
    }

    private static string ToCamelIdentifier(string value)
    {
        var pascal = ToPascalIdentifier(value);
        return pascal.Length == 1
            ? pascal.ToLowerInvariant()
            : char.ToLowerInvariant(pascal[0]) + pascal.Substring(1);
    }

    private static string EscapeString(string value)
        => Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(value, quote: false);

    private sealed record OperationModel(
        string Name,
        string HttpMethod,
        string Route,
        IReadOnlyList<ParameterModel> Parameters,
        string? RequestType,
        bool RequestRequired,
        string? RequestContentType,
        string? ResponseType);

    private sealed record ParameterModel(OpenApiParameter Parameter, string VariableName, string TypeName);

    private sealed class NameAllocator
    {
        private readonly HashSet<string> _used;

        public NameAllocator(IEnumerable<string>? reserved = null)
        {
            _used = reserved is null
                ? new HashSet<string>(StringComparer.Ordinal)
                : new HashSet<string>(reserved, StringComparer.Ordinal);
        }

        public string Allocate(string preferred)
        {
            if (_used.Add(preferred))
                return preferred;

            for (var suffix = 2; ; suffix++)
            {
                var candidate = preferred + suffix.ToString(CultureInfo.InvariantCulture);
                if (_used.Add(candidate))
                    return candidate;
            }
        }
    }

    private sealed class TypeRegistry
    {
        private readonly OpenApiDocument _document;
        private readonly Dictionary<string, GeneratedType> _typesByName = new(StringComparer.Ordinal);
        private readonly HashSet<string> _reservedNames;
        private readonly HashSet<OpenApiSchema> _resolvingTypes = new();

        public TypeRegistry(OpenApiDocument document, IEnumerable<string> reservedNames)
        {
            _document = document;
            _reservedNames = new HashSet<string>(reservedNames, StringComparer.Ordinal);
            _reservedNames.UnionWith([
                "HttpClient", "HttpRequestException", "HttpStatusCode", "HttpRequestMessage", "HttpMethod",
                "HttpCompletionOption", "JsonContent", "JsonException", "JsonSerializer", "JsonElement",
                "JsonConverter", "JsonStringEnumConverter", "JsonStringEnumMemberName", "JsonPropertyName",
                "JsonExtensionData", "JsonIgnore", "JsonIgnoreCondition", "Task", "CancellationToken", "IServiceCollection", "Action", "Uri",
                "UriKind", "UriBuilder", "StringComparison", "CultureInfo", "Enum", "IFormattable", "Guid", "DateOnly",
                "DateTimeOffset", "List", "Dictionary", "IReadOnlyList"
            ]);
            foreach (var schema in document.Schemas.OrderBy(static pair => pair.Key, StringComparer.Ordinal))
            {
                if (NeedsGeneratedType(schema.Value))
                    Register(ToPascalIdentifier(schema.Key), ToPascalIdentifier(schema.Key), schema.Value);
            }
        }

        public List<GeneratedType> GeneratedTypes { get; } = new();

        public string GetTypeName(OpenApiSchema schema, string preferredName, string qualifiedName, bool required, SchemaScope scope = SchemaScope.Neutral)
        {
            if (!_resolvingTypes.Add(schema))
                throw new ClientGenerationException("Recursive array or dictionary aliases are not supported.");
            try
            {
                if (scope != SchemaScope.Neutral && !HasDirectionalProperties(schema, new HashSet<OpenApiSchema>()))
                    scope = SchemaScope.Neutral;
                var typeName = GetNonNullableTypeName(schema, preferredName, qualifiedName, scope);
                if (required && !schema.Nullable && !ResolveSchema(schema).Nullable)
                    return typeName;

                return typeName.EndsWith("?", StringComparison.Ordinal) ? typeName : typeName + "?";
            }
            finally
            {
                _resolvingTypes.Remove(schema);
            }
        }

        private bool HasDirectionalProperties(OpenApiSchema schema, HashSet<OpenApiSchema> visited)
        {
            schema = ResolveSchema(schema);
            if (!visited.Add(schema))
                return false;
            return schema.Properties.Any(property => property.Value.ReadOnly || property.Value.WriteOnly ||
                       HasDirectionalProperties(property.Value, visited)) ||
                   schema.AllOf.Any(part => HasDirectionalProperties(part, visited)) ||
                   schema.Items is { } items && HasDirectionalProperties(items, visited) ||
                   schema.AdditionalProperties is { } additional && HasDirectionalProperties(additional, visited);
        }

        public OpenApiSchema ResolveSchema(OpenApiSchema schema)
        {
            var visited = new HashSet<string>(StringComparer.Ordinal);
            while (!string.IsNullOrWhiteSpace(schema.Reference))
            {
                var reference = schema.Reference!;
                if (!visited.Add(reference))
                    throw new ClientGenerationException($"Cyclic schema reference '{reference}'.");
                if (!_document.Schemas.TryGetValue(reference, out var resolved))
                    throw new ClientGenerationException($"Unable to resolve schema reference '{reference}'.");
                schema = resolved;
            }
            return schema;
        }

        public IReadOnlyDictionary<string, OpenApiSchema> GetEffectiveProperties(OpenApiSchema schema)
        {
            var result = new Dictionary<string, OpenApiSchema>(StringComparer.Ordinal);
            AddProperties(schema, result, new HashSet<string>(StringComparer.Ordinal));
            return result;
        }

        public bool IsRequired(OpenApiSchema schema, string propertyName)
        {
            var required = new HashSet<string>(StringComparer.Ordinal);
            AddRequired(schema, required, new HashSet<string>(StringComparer.Ordinal));
            return required.Contains(propertyName);
        }

        private string GetNonNullableTypeName(OpenApiSchema schema, string preferredName, string qualifiedName, SchemaScope scope)
        {
            _ = ResolveSchema(schema);
            var reference = schema.Reference ?? string.Empty;
            if (!string.IsNullOrWhiteSpace(reference))
            {
                if (_document.Schemas.TryGetValue(reference, out var referenced))
                {
                    if (NeedsGeneratedType(referenced))
                    {
                        var name = ToPascalIdentifier(reference) + (scope == SchemaScope.Neutral ? string.Empty : scope.ToString());
                        return Register(name, name, referenced, scope);
                    }
                    return GetTypeName(referenced, preferredName, qualifiedName, required: true, scope);
                }

                throw new ClientGenerationException($"Unable to resolve schema reference '{reference}'.");
            }

            if (schema.Enum is { Count: > 0 })
                return Register(preferredName, qualifiedName, schema, scope);

            if (schema.Type == "array")
            {
                var itemType = schema.Items is null
                    ? "object"
                    : GetTypeName(schema.Items, preferredName + "Item", qualifiedName + "Item", required: true, scope);
                return $"IReadOnlyList<{itemType}>";
            }

            if ((schema.Type == "object" || schema.Type is null) &&
                schema.Properties.Count == 0 &&
                schema.AllOf.Count == 0 &&
                (schema.AdditionalProperties is not null || schema.AdditionalPropertiesAllowed))
            {
                var valueType = schema.AdditionalProperties is null
                    ? "object"
                    : GetTypeName(schema.AdditionalProperties, preferredName + "Value", qualifiedName + "Value", required: true, scope);
                return $"Dictionary<string, {valueType}>";
            }

            if (NeedsGeneratedType(schema))
                return Register(preferredName, qualifiedName, schema, scope);

            return schema.Type switch
            {
                "string" when schema.Format == "uuid" => "Guid",
                "string" when schema.Format == "date-time" => "DateTimeOffset",
                "string" when schema.Format == "date" => "DateOnly",
                "string" => "string",
                "integer" when schema.Format == "int64" => "long",
                "integer" => "int",
                "number" when schema.Format == "float" => "float",
                "number" => "double",
                "boolean" => "bool",
                "object" => "object",
                _ => "object"
            };
        }

        private string Register(string preferredName, string qualifiedName, OpenApiSchema schema, SchemaScope scope = SchemaScope.Neutral)
        {
            if (schema.Enum is { Count: > 0 } && schema.Type != "string")
                throw new ClientGenerationException("Only string enums are supported.");
            var fingerprint = Fingerprint(schema);
            foreach (var candidate in CandidateNames(preferredName, qualifiedName))
            {
                if (_reservedNames.Contains(candidate))
                    continue;

                if (!_typesByName.TryGetValue(candidate, out var existing))
                    return Add(candidate, schema, scope);

                if (existing.Scope == scope && Fingerprint(existing.Schema) == fingerprint)
                    return candidate;
            }

            throw new InvalidOperationException("Unable to allocate generated type name.");
        }

        private static IEnumerable<string> CandidateNames(string preferredName, string qualifiedName)
        {
            var preferred = ToPascalIdentifier(preferredName);
            var qualified = ToPascalIdentifier(qualifiedName);
            yield return preferred;
            if (!string.Equals(qualified, preferred, StringComparison.Ordinal))
                yield return qualified;
            yield return qualified + "Model";
            for (var suffix = 2; ; suffix++)
                yield return qualified + suffix.ToString(CultureInfo.InvariantCulture);
        }

        private string Add(string name, OpenApiSchema schema, SchemaScope scope)
        {
            var generated = new GeneratedType(name, schema, scope);
            _typesByName.Add(name, generated);
            GeneratedTypes.Add(generated);
            return name;
        }

        private static bool NeedsGeneratedType(OpenApiSchema schema)
            => schema.Enum is { Count: > 0 } ||
               schema.Properties.Count > 0 ||
               schema.AllOf.Count > 0;

        private void AddProperties(
            OpenApiSchema schema,
            Dictionary<string, OpenApiSchema> target,
            HashSet<string> visitedReferences)
        {
            var reference = schema.Reference ?? string.Empty;
            if (!string.IsNullOrWhiteSpace(reference) && visitedReferences.Add(reference))
            {
                if (!_document.Schemas.TryGetValue(reference, out var referenced))
                    throw new ClientGenerationException($"Unable to resolve schema reference '{reference}'.");
                AddProperties(referenced, target, visitedReferences);
            }

            foreach (var part in schema.AllOf)
                AddProperties(part, target, visitedReferences);

            foreach (var property in schema.Properties)
            {
                if (target.TryGetValue(property.Key, out var existing) && Fingerprint(existing) != Fingerprint(property.Value))
                    throw new ClientGenerationException($"Conflicting allOf property '{property.Key}' is not supported.");
                target[property.Key] = property.Value;
            }
        }

        private void AddRequired(OpenApiSchema schema, HashSet<string> target, HashSet<string> visitedReferences)
        {
            var reference = schema.Reference ?? string.Empty;
            if (!string.IsNullOrWhiteSpace(reference) &&
                visitedReferences.Add(reference) &&
                _document.Schemas.TryGetValue(reference, out var referenced))
            {
                AddRequired(referenced, target, visitedReferences);
            }

            foreach (var part in schema.AllOf)
                AddRequired(part, target, visitedReferences);

            foreach (var required in schema.Required)
                target.Add(required);
        }

        private static string Fingerprint(OpenApiSchema schema)
        {
            var builder = new StringBuilder();
            AppendFingerprint(builder, schema);
            return builder.ToString();
        }

        private static void AppendFingerprint(StringBuilder builder, OpenApiSchema schema)
        {
            builder.Append(schema.Reference).Append('|')
                .Append(schema.Type).Append('|')
                .Append(schema.Format).Append('|')
                .Append(schema.Nullable).Append('|')
                .Append(schema.ReadOnly).Append('|')
                .Append(schema.WriteOnly).Append('|')
                .Append(schema.AdditionalPropertiesAllowed).Append('|');

            if (schema.Enum is { } values)
            {
                foreach (var value in values)
                    builder.Append("e:").Append(value).Append(';');
            }

            foreach (var required in schema.Required.OrderBy(static value => value, StringComparer.Ordinal))
                builder.Append("r:").Append(required).Append(';');

            foreach (var property in schema.Properties.OrderBy(static pair => pair.Key, StringComparer.Ordinal))
            {
                builder.Append("p:").Append(property.Key).Append('{');
                AppendFingerprint(builder, property.Value);
                builder.Append('}');
            }

            foreach (var part in schema.AllOf)
            {
                builder.Append("a{");
                AppendFingerprint(builder, part);
                builder.Append('}');
            }

            if (schema.Items is not null)
            {
                builder.Append("i{");
                AppendFingerprint(builder, schema.Items);
                builder.Append('}');
            }

            if (schema.AdditionalProperties is not null)
            {
                builder.Append("x{");
                AppendFingerprint(builder, schema.AdditionalProperties);
                builder.Append('}');
            }
        }
    }

    private enum SchemaScope { Neutral, Request, Response }

    private sealed record GeneratedType(string Name, OpenApiSchema Schema, SchemaScope Scope);
}

internal sealed class ClientGenerationException(string message) : Exception(message);