using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;

using MinimalOpenAPI.Samples.ResponseResults.Openapi.Contracts;
using MinimalOpenAPI.Samples.ResponseResults.Openapi.Endpoints;

namespace MinimalOpenAPI.Samples.ResponseResults;

/// <summary>
/// Demonstrates <c>Created&lt;Order&gt;</c> plus a schema-less <c>BadRequestProblem</c> wrapper.
/// The <c>BadRequestProblem</c> type is generated by MinimalOpenAPI when a response declares
/// <c>application/problem+json</c> with no schema.
/// </summary>
public sealed class CreateOrderHandler : CreateOrderEndpointBase
{
    private readonly InMemoryOrderStore _store;

    public CreateOrderHandler(InMemoryOrderStore store) => _store = store;

    public override Task<Results<Created<Order>, BadRequestProblem>> HandleAsync(
        Request request,
        CancellationToken cancellationToken)
    {
        if (request.Amount < 0)
        {
            return Task.FromResult<Results<Created<Order>, BadRequestProblem>>(
                new BadRequestProblem(new ProblemDetails
                {
                    Title = "Invalid amount",
                    Detail = "Amount must be zero or positive."
                }));
        }

        var order = _store.Add(request.ExternalReference, request.CustomerName, request.Amount);
        return Task.FromResult<Results<Created<Order>, BadRequestProblem>>(
            TypedResults.Created($"/orders/{order.Id}", order));
    }
}